Friend Module ItemTypePopulator
    Private Sub PopulateItemTypesRecord(connection As SqliteConnection, ItemTypeId As Long, ItemTypeName As String)
        Using command = New SqliteCommand(
            $"INSERT INTO [{Tables.ItemTypes}]
            (
                [{Columns.ItemTypeIdColumn}], 
                [{Columns.ItemTypeNameColumn}]
            ) 
            VALUES 
            (
                @{Columns.ItemTypeIdColumn}, 
                @{Columns.ItemTypeNameColumn}
            );", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeNameColumn}", ItemTypeName)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Friend Sub PopulateItemTypes(connection As SqliteConnection)
        PopulateItemTypesRecord(connection, ItemType1, "FE Key")
        PopulateItemTypesRecord(connection, ItemType2, "CU Key")
        PopulateItemTypesRecord(connection, ItemType3, "AG Key")
        PopulateItemTypesRecord(connection, ItemType4, "AU Key")
        PopulateItemTypesRecord(connection, ItemType5, "PT Key")
        PopulateItemTypesRecord(connection, ItemType6, "Elemental Orb")
        PopulateItemTypesRecord(connection, ItemType7, "Potion")
        PopulateItemTypesRecord(connection, ItemType8, "Goblin Ear")
        PopulateItemTypesRecord(connection, ItemType9, "Skull Fragment")
        PopulateItemTypesRecord(connection, ItemType10, "Dagger")
        PopulateItemTypesRecord(connection, ItemType11, "Earth Shard")
        PopulateItemTypesRecord(connection, ItemType12, "Water Shard")
        PopulateItemTypesRecord(connection, ItemType13, "Fire Shard")
        PopulateItemTypesRecord(connection, ItemType14, "Air Shard")
        PopulateItemTypesRecord(connection, ItemType15, "Shield")
        PopulateItemTypesRecord(connection, ItemType16, "Helmet")
        PopulateItemTypesRecord(connection, ItemType17, "Chainmail")
        PopulateItemTypesRecord(connection, ItemType18, "Shortsword")
        PopulateItemTypesRecord(connection, ItemType19, "Brodesode")
        PopulateItemTypesRecord(connection, ItemType20, "Platemail")
        PopulateItemTypesRecord(connection, ItemType21, "Rat Tail")
        PopulateItemTypesRecord(connection, ItemType22, "Holy ""Water""")
        PopulateItemTypesRecord(connection, ItemType23, "Town Portal")
        PopulateItemTypesRecord(connection, ItemType24, "kottbulle")
        PopulateItemTypesRecord(connection, ItemType25, "Magic Egg")
        PopulateItemTypesRecord(connection, ItemType26, "Beer")
        PopulateItemTypesRecord(connection, ItemType27, "Trousers")
        PopulateItemTypesRecord(connection, ItemType28, "Pr0n Scroll")
        PopulateItemTypesRecord(connection, ItemType29, "Moon Portal")
        PopulateItemTypesRecord(connection, ItemType30, "Empty Bottle")
        PopulateItemTypesRecord(connection, ItemType31, "Book of Holy Bolt")
        PopulateItemTypesRecord(connection, ItemType32, "Membership Card")
        PopulateItemTypesRecord(connection, ItemType33, "Bong")
        PopulateItemTypesRecord(connection, ItemType34, """Herb""")
        PopulateItemTypesRecord(connection, ItemType35, "kottbulle")
        PopulateItemTypesRecord(connection, ItemType36, "Mushroom")
        PopulateItemTypesRecord(connection, ItemType37, "Rotten Egg")
        PopulateItemTypesRecord(connection, ItemType38, "Zombie Taint")
        PopulateItemTypesRecord(connection, ItemType39, "Lotion")
        PopulateItemTypesRecord(connection, ItemType40, "Bat Wing")
        PopulateItemTypesRecord(connection, ItemType41, "Snake Fang")
        PopulateItemTypesRecord(connection, ItemType42, "Shoe Laces")
        PopulateItemTypesRecord(connection, ItemType43, "Spacesord")
        PopulateItemTypesRecord(connection, ItemType44, "Horns of Kordanor")
        PopulateItemTypesRecord(connection, ItemType45, "Amulet of HP")
        PopulateItemTypesRecord(connection, ItemType46, "Ring of HP")
        PopulateItemTypesRecord(connection, ItemType47, "Book of Purify")
        PopulateItemTypesRecord(connection, ItemType48, "Amulet of STR")
        PopulateItemTypesRecord(connection, ItemType49, "Amulet of DEX")
        PopulateItemTypesRecord(connection, ItemType50, "Amulet of POW")
        PopulateItemTypesRecord(connection, ItemType51, "Amulet of Mana")
        PopulateItemTypesRecord(connection, ItemType52, "Amulet of Yendor")
        PopulateItemTypesRecord(connection, ItemType53, "Note")
    End Sub
    Private Sub PopulateItemTypeShopTypesRecord(connection As SqliteConnection, ItemTypeId As Long, ShoppeTypeId As Long, TransactionTypeId As Long)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypeShopTypes}]([{Columns.ItemTypeIdColumn}], [{Columns.ShoppeTypeIdColumn}], [{Columns.TransactionTypeIdColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.ShoppeTypeIdColumn}, @{Columns.TransactionTypeIdColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.ShoppeTypeIdColumn}", ShoppeTypeId)
            command.Parameters.AddWithValue($"@{Columns.TransactionTypeIdColumn}", TransactionTypeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Friend Const TransactionTypeOffer = 1L
    Friend Const TransactionTypePrice = 2L
    Friend Const TransactionTypeRepair = 3L
    Sub PopulateItemTypeShopTypes(connection As SqliteConnection)
        PopulateItemTypeShopTypesRecord(connection, ItemType7, ShoppeType4, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType8, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType9, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType10, ShoppeType2, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType10, ShoppeType2, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType10, ShoppeType2, TransactionTypeRepair)
        PopulateItemTypeShopTypesRecord(connection, ItemType15, ShoppeType2, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType15, ShoppeType2, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType15, ShoppeType2, TransactionTypeRepair)
        PopulateItemTypeShopTypesRecord(connection, ItemType16, ShoppeType2, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType16, ShoppeType2, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType16, ShoppeType2, TransactionTypeRepair)
        PopulateItemTypeShopTypesRecord(connection, ItemType17, ShoppeType2, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType17, ShoppeType2, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType17, ShoppeType2, TransactionTypeRepair)
        PopulateItemTypeShopTypesRecord(connection, ItemType18, ShoppeType2, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType18, ShoppeType2, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType18, ShoppeType2, TransactionTypeRepair)
        PopulateItemTypeShopTypesRecord(connection, ItemType19, ShoppeType2, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType19, ShoppeType2, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType29, ShoppeType2, TransactionTypeRepair)
        PopulateItemTypeShopTypesRecord(connection, ItemType20, ShoppeType2, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType20, ShoppeType2, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType20, ShoppeType2, TransactionTypeRepair)
        PopulateItemTypeShopTypesRecord(connection, ItemType21, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType22, ShoppeType4, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType23, ShoppeType1, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType24, ShoppeType3, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType25, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType26, ShoppeType3, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType27, ShoppeType5, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType28, ShoppeType5, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType29, ShoppeType1, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType31, ShoppeType1, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType33, ShoppeType1, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType34, ShoppeType1, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType36, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType38, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType39, ShoppeType5, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType40, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType41, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType47, ShoppeType1, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType52, ShoppeType5, TransactionTypePrice)
    End Sub
    Sub PopulateItemTypeEventsRecord(connection As SqliteConnection, ItemTypeId As Long, EventId As Long, EventName As String)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypeEvents}]([{Columns.ItemTypeIdColumn}], [{Columns.EventIdColumn}], [{Columns.EventNameColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.EventIdColumn}, @{Columns.EventNameColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.EventIdColumn}", EventId)
            command.Parameters.AddWithValue($"@{Columns.EventNameColumn}", EventName)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Friend Const EventTypePurify = 1L
    Friend Const EventTypeCanUse = 2L
    Friend Const EventTypeUse = 3L
    Friend Const EventTypeDecay = 4L
    Friend Const EventTypeAddToInventory = 5L
    Sub PopulateItemTypeEvents(connection As SqliteConnection)
        PopulateItemTypeEventsRecord(connection, ItemType7, EventTypeCanUse, "AlwaysTrue")
        PopulateItemTypeEventsRecord(connection, ItemType7, EventTypeUse, "DrinkPotion")
        PopulateItemTypeEventsRecord(connection, ItemType11, EventTypeCanUse, "CanUseEarthShard")
        PopulateItemTypeEventsRecord(connection, ItemType11, EventTypeUse, "UseEarthShard")
        PopulateItemTypeEventsRecord(connection, ItemType12, EventTypeCanUse, "CanUseWaterShard")
        PopulateItemTypeEventsRecord(connection, ItemType12, EventTypeUse, "UseWaterShard")
        PopulateItemTypeEventsRecord(connection, ItemType13, EventTypeCanUse, "CanUseFireShard")
        PopulateItemTypeEventsRecord(connection, ItemType13, EventTypeUse, "UseFireShard")
        PopulateItemTypeEventsRecord(connection, ItemType14, EventTypeCanUse, "CanUseAirShard")
        PopulateItemTypeEventsRecord(connection, ItemType14, EventTypeUse, "UseAirShard")
        PopulateItemTypeEventsRecord(connection, ItemType22, EventTypeCanUse, "IsFightingUndead")
        PopulateItemTypeEventsRecord(connection, ItemType22, EventTypeUse, "UseHolyWater")
        PopulateItemTypeEventsRecord(connection, ItemType23, EventTypeCanUse, "IsInDungeon")
        PopulateItemTypeEventsRecord(connection, ItemType23, EventTypeUse, "UseTownPortal")
        PopulateItemTypeEventsRecord(connection, ItemType24, EventTypeCanUse, "AlwaysTrue")
        PopulateItemTypeEventsRecord(connection, ItemType24, EventTypeUse, "EatFood")
        PopulateItemTypeEventsRecord(connection, ItemType25, EventTypeCanUse, "AlwaysTrue")
        PopulateItemTypeEventsRecord(connection, ItemType25, EventTypeUse, "UseMagicEgg")
        PopulateItemTypeEventsRecord(connection, ItemType26, EventTypeCanUse, "CanUseBeer")
        PopulateItemTypeEventsRecord(connection, ItemType26, EventTypeUse, "UseBeer")
        PopulateItemTypeEventsRecord(connection, ItemType28, EventTypeCanUse, "CanUsePr0n")
        PopulateItemTypeEventsRecord(connection, ItemType28, EventTypeUse, "UsePr0n")
        PopulateItemTypeEventsRecord(connection, ItemType29, EventTypeCanUse, "IsInDungeon")
        PopulateItemTypeEventsRecord(connection, ItemType29, EventTypeUse, "UseMoonPortal")
        PopulateItemTypeEventsRecord(connection, ItemType30, EventTypeCanUse, "CanUseBottle")
        PopulateItemTypeEventsRecord(connection, ItemType30, EventTypeUse, "UseBottle")
        PopulateItemTypeEventsRecord(connection, ItemType31, EventTypeCanUse, "CanLearnHolyBolt")
        PopulateItemTypeEventsRecord(connection, ItemType31, EventTypeUse, "LearnHolyBolt")
        PopulateItemTypeEventsRecord(connection, ItemType34, EventTypeCanUse, "HasBong")
        PopulateItemTypeEventsRecord(connection, ItemType34, EventTypeUse, "UseHerb")
        PopulateItemTypeEventsRecord(connection, ItemType35, EventTypePurify, "PurifyFood")
        PopulateItemTypeEventsRecord(connection, ItemType35, EventTypeCanUse, "AlwaysTrue")
        PopulateItemTypeEventsRecord(connection, ItemType35, EventTypeUse, "UseRottenFood")
        PopulateItemTypeEventsRecord(connection, ItemType37, EventTypeCanUse, "CanUseRottenEgg")
        PopulateItemTypeEventsRecord(connection, ItemType37, EventTypeUse, "UseRottenEgg")
        PopulateItemTypeEventsRecord(connection, ItemType47, EventTypeCanUse, "CanLearnPurify")
        PopulateItemTypeEventsRecord(connection, ItemType47, EventTypeUse, "LearnPurify")
        PopulateItemTypeEventsRecord(connection, ItemType24, EventTypeDecay, "FoodDecay")
        PopulateItemTypeEventsRecord(connection, ItemType35, EventTypeDecay, "RottenFoodDecay")
        PopulateItemTypeEventsRecord(connection, ItemType53, EventTypeCanUse, "AlwaysTrue")
        PopulateItemTypeEventsRecord(connection, ItemType53, EventTypeUse, "ReadNote")
    End Sub
    Private Sub PopulateItemTypeEquipSlotsRecord(connection As SqliteConnection, ItemTypeId As Long, EquipSlotId As Long)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypeEquipSlots}]([{Columns.ItemTypeIdColumn}], [{Columns.EquipSlotIdColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.EquipSlotIdColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.EquipSlotIdColumn}", EquipSlotId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Friend Sub PopulateItemTypeEquipSlots(connection As SqliteConnection)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType10, EquipSlot1)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType15, EquipSlot2)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType16, EquipSlot3)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType17, EquipSlot4)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType18, EquipSlot1)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType19, EquipSlot1)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType20, EquipSlot4)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType27, EquipSlot5)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType30, EquipSlot1)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType43, EquipSlot1)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType45, EquipSlot6)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType46, EquipSlot7)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType46, EquipSlot8)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType48, EquipSlot6)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType49, EquipSlot6)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType50, EquipSlot6)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType51, EquipSlot6)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType52, EquipSlot6)
    End Sub
    Sub PopulateItemTypeSpawnCountsRecord(connection As SqliteConnection, ItemTypeId As Long, DungeonLevelId As Long, SpawnDice As String)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypeSpawnCounts}]([{Columns.ItemTypeIdColumn}], [{Columns.DungeonLevelIdColumn}], [{Columns.SpawnDiceColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.DungeonLevelIdColumn}, @{Columns.SpawnDiceColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.DungeonLevelIdColumn}", DungeonLevelId)
            command.Parameters.AddWithValue($"@{Columns.SpawnDiceColumn}", SpawnDice)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypeSpawnCounts(connection As SqliteConnection)
        PopulateItemTypeSpawnCountsRecord(connection, ItemType7, DungeonLevel1, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType7, DungeonLevel2, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType7, DungeonLevel3, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType7, DungeonLevel4, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType7, DungeonLevel5, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType10, DungeonLevel1, "4d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType10, DungeonLevel2, "2d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType11, DungeonLevel2, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType12, DungeonLevel4, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType13, DungeonLevel3, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType14, DungeonLevel1, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType15, DungeonLevel1, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType16, DungeonLevel1, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType17, DungeonLevel1, "1d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType18, DungeonLevel1, "2d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType18, DungeonLevel2, "1d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType19, DungeonLevel2, "2d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType19, DungeonLevel3, "1d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType20, DungeonLevel2, "1d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType43, DungeonLevel6, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType45, DungeonLevel1, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType48, DungeonLevel4, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType50, DungeonLevel3, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType51, DungeonLevel5, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType53, DungeonLevel1, "5d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType53, DungeonLevel2, "5d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType53, DungeonLevel3, "5d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType53, DungeonLevel4, "5d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType53, DungeonLevel5, "5d1")
    End Sub
    Sub PopulateItemTypeSpawnLocationTypesRecord(connection As SqliteConnection, ItemTypeId As Long, DungeonLevelId As Long, LocationTypeId As Long)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypeSpawnLocationTypes}]([{Columns.ItemTypeIdColumn}], [{Columns.DungeonLevelIdColumn}], [{Columns.LocationTypeIdColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.DungeonLevelIdColumn}, @{Columns.LocationTypeIdColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.DungeonLevelIdColumn}", DungeonLevelId)
            command.Parameters.AddWithValue($"@{Columns.LocationTypeIdColumn}", LocationTypeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypeSpawnLocationTypes(connection As SqliteConnection)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType1, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType1, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType1, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType1, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType1, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType2, DungeonLevel1, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType3, DungeonLevel2, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType4, DungeonLevel3, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType5, DungeonLevel4, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel1, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel2, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel3, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel4, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel5, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType10, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType10, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType10, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType10, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType10, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType11, DungeonLevel2, LocationType6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType12, DungeonLevel4, LocationType6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType14, DungeonLevel1, LocationType6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel1, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel2, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel3, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel4, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel5, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel1, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel2, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel3, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel4, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel5, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel1, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel2, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel3, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel4, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel5, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType18, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType18, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType18, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType18, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType18, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType19, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType19, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType19, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType19, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType19, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType20, DungeonLevel2, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType20, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType20, DungeonLevel3, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType20, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType20, DungeonLevel4, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType20, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType20, DungeonLevel5, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType43, DungeonLevel6, LocationType8)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType45, DungeonLevel1, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType45, DungeonLevel1, LocationType6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType48, DungeonLevel4, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType48, DungeonLevel4, LocationType6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType50, DungeonLevel3, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType50, DungeonLevel3, LocationType6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType51, DungeonLevel2, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType51, DungeonLevel2, LocationType6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType53, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType53, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType53, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType53, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType53, DungeonLevel5, LocationType4)
    End Sub
    Sub PopulateItemTypeCharacterStatisticBuffsRecord(connection As SqliteConnection, ItemTypeId As Long, CharacterStatisticTypeId As Long, Buff As Long)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypeCharacterStatisticBuffs}]([{Columns.ItemTypeIdColumn}], [{Columns.StatisticTypeIdColumn}], [{Columns.BuffColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.StatisticTypeIdColumn}, @{Columns.BuffColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.StatisticTypeIdColumn}", CharacterStatisticTypeId)
            command.Parameters.AddWithValue($"@{Columns.BuffColumn}", Buff)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypeCharacterStatisticBuffs(connection As SqliteConnection)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, ItemType45, StatisticTypeHP, 1)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, ItemType46, StatisticTypeHP, 1)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, ItemType49, StatisticTypeDexterity, 1)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, ItemType50, StatisticTypePower, 1)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, ItemType51, StatisticTypeMana, 1)
    End Sub
    Private Sub PopulateItemTypeStatisticsRecord(connection As SqliteConnection, ItemTypeId As Long, ItemTypeStatisticTypeId As Long, ItemTypeStatisticValue As Long)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypeStatistics}]([{Columns.ItemTypeIdColumn}], [{Columns.StatisticTypeIdColumn}], [{Columns.StatisticValueColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.StatisticTypeIdColumn}, @{Columns.StatisticValueColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.StatisticTypeIdColumn}", ItemTypeStatisticTypeId)
            command.Parameters.AddWithValue($"@{Columns.StatisticValueColumn}", ItemTypeStatisticValue)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Friend Sub PopulateItemTypeStatistics(connection As SqliteConnection)
        PopulateItemTypeStatisticsRecord(connection, ItemType7, StatisticTypeEncumbrance, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType7, StatisticTypePrice, 15)
        PopulateItemTypeStatisticsRecord(connection, ItemType8, StatisticTypeOffer, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType9, StatisticTypeOffer, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, StatisticTypeEncumbrance, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, StatisticTypeAttackDice, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, StatisticTypeMaximumDamage, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, StatisticTypeMaximumDurability, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, StatisticTypeOffer, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, StatisticTypePrice, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, StatisticTypeRepairPrice, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType15, StatisticTypeEncumbrance, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType15, StatisticTypeDefendDice, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType15, StatisticTypeMaximumDurability, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType15, StatisticTypeOffer, 3)
        PopulateItemTypeStatisticsRecord(connection, ItemType15, StatisticTypePrice, 15)
        PopulateItemTypeStatisticsRecord(connection, ItemType15, StatisticTypeRepairPrice, 6)
        PopulateItemTypeStatisticsRecord(connection, ItemType16, StatisticTypeEncumbrance, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType16, StatisticTypeDefendDice, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType16, StatisticTypeMaximumDurability, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType16, StatisticTypeOffer, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType16, StatisticTypePrice, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType16, StatisticTypeRepairPrice, 4)
        PopulateItemTypeStatisticsRecord(connection, ItemType17, StatisticTypeEncumbrance, 20)
        PopulateItemTypeStatisticsRecord(connection, ItemType17, StatisticTypeMaximumDamage, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType17, StatisticTypeDefendDice, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType17, StatisticTypeOffer, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType17, StatisticTypePrice, 50)
        PopulateItemTypeStatisticsRecord(connection, ItemType17, StatisticTypeRepairPrice, 20)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, StatisticTypeEncumbrance, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, StatisticTypeMaximumDamage, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, StatisticTypeAttackDice, 4)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, StatisticTypeMaximumDurability, 20)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, StatisticTypeOffer, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, StatisticTypePrice, 25)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, StatisticTypeRepairPrice, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, StatisticTypeEncumbrance, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, StatisticTypeAttackDice, 6)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, StatisticTypeMaximumDamage, 3)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, StatisticTypeMaximumDurability, 40)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, StatisticTypeOffer, 20)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, StatisticTypePrice, 100)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, StatisticTypeRepairPrice, 40)
        PopulateItemTypeStatisticsRecord(connection, ItemType20, StatisticTypeEncumbrance, 40)
        PopulateItemTypeStatisticsRecord(connection, ItemType20, StatisticTypeDefendDice, 4)
        PopulateItemTypeStatisticsRecord(connection, ItemType20, StatisticTypeMaximumDurability, 50)
        PopulateItemTypeStatisticsRecord(connection, ItemType20, StatisticTypeOffer, 50)
        PopulateItemTypeStatisticsRecord(connection, ItemType20, StatisticTypePrice, 250)
        PopulateItemTypeStatisticsRecord(connection, ItemType20, StatisticTypeRepairPrice, 100)
        PopulateItemTypeStatisticsRecord(connection, ItemType21, StatisticTypeOffer, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType22, StatisticTypePrice, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType23, StatisticTypePrice, 50)
        PopulateItemTypeStatisticsRecord(connection, ItemType24, StatisticTypePrice, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType25, StatisticTypeOffer, 100)
        PopulateItemTypeStatisticsRecord(connection, ItemType26, StatisticTypeEncumbrance, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType26, StatisticTypePrice, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType27, StatisticTypePrice, 100)
        PopulateItemTypeStatisticsRecord(connection, ItemType28, StatisticTypePrice, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType29, StatisticTypePrice, 5000)
        PopulateItemTypeStatisticsRecord(connection, ItemType30, StatisticTypeEncumbrance, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType30, StatisticTypeAttackDice, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType30, StatisticTypeMaximumDamage, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType30, StatisticTypeMaximumDurability, 3)
        PopulateItemTypeStatisticsRecord(connection, ItemType31, StatisticTypePrice, 100)
        PopulateItemTypeStatisticsRecord(connection, ItemType32, StatisticTypeOffer, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType33, StatisticTypePrice, 25)
        PopulateItemTypeStatisticsRecord(connection, ItemType34, StatisticTypePrice, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType36, StatisticTypeOffer, 25)
        PopulateItemTypeStatisticsRecord(connection, ItemType38, StatisticTypeOffer, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType39, StatisticTypeEncumbrance, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType39, StatisticTypeOffer, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType39, StatisticTypePrice, 25)
        PopulateItemTypeStatisticsRecord(connection, ItemType40, StatisticTypeOffer, 3)
        PopulateItemTypeStatisticsRecord(connection, ItemType41, StatisticTypeOffer, 3)
        PopulateItemTypeStatisticsRecord(connection, ItemType43, StatisticTypeEncumbrance, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType43, StatisticTypeMaximumDamage, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType43, StatisticTypeDefendDice, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType43, StatisticTypeOffer, 100)
        PopulateItemTypeStatisticsRecord(connection, ItemType47, StatisticTypePrice, 50)
        PopulateItemTypeStatisticsRecord(connection, ItemType52, StatisticTypePrice, 1000)
        PopulateItemTypeStatisticsRecord(connection, ItemType1, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType2, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType3, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType4, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType5, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType6, StatisticTypeSingleUse, 0)
        PopulateItemTypeStatisticsRecord(connection, ItemType7, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType8, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType9, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType11, StatisticTypeSingleUse, 0)
        PopulateItemTypeStatisticsRecord(connection, ItemType12, StatisticTypeSingleUse, 0)
        PopulateItemTypeStatisticsRecord(connection, ItemType13, StatisticTypeSingleUse, 0)
        PopulateItemTypeStatisticsRecord(connection, ItemType14, StatisticTypeSingleUse, 0)
        PopulateItemTypeStatisticsRecord(connection, ItemType15, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType16, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType17, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType20, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType21, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType22, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType23, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType24, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType25, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType26, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType27, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType28, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType29, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType30, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType31, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType32, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType33, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType34, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType35, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType36, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType37, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType38, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType39, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType40, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType41, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType42, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType43, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType44, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType45, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType46, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType47, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType48, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType49, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType50, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType51, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType52, StatisticTypeSingleUse, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType53, StatisticTypeSingleUse, 0)
    End Sub
    Public Sub PopulateItemLores(connection As SqliteConnection)
    End Sub
    Public Const LoreType1 = 1L
    Public Const LoreType2 = 2L
    Public Const LoreType3 = 3L
    Public Const LoreType4 = 4L
    Public Const LoreType5 = 5L
    Public Const LoreType6 = 6L
    Public Const LoreType7 = 7L
    Public Const LoreType8 = 8L
    Public Const LoreType9 = 9L
    Public Const LoreType10 = 10L
    Public Const LoreType11 = 11L
    Public Const LoreType12 = 12L
    Public Const LoreType13 = 13L
    Public Const LoreType14 = 14L
    Public Const LoreType15 = 15L
    Public Const LoreType16 = 16L
    Public Const LoreType17 = 17L
    Public Const LoreType18 = 18L
    Public Const LoreType19 = 19L
    Public Const LoreType20 = 20L
    Public Const LoreType21 = 21L
    Public Const LoreType22 = 22L
    Public Const LoreType23 = 23L
    Public Const LoreType24 = 24L
    Public Const LoreType25 = 25L
    Friend Sub PopulateLores(connection As SqliteConnection)
        PopulateLoreRecord(connection, LoreType1, "Genso Manifest Pg137", "My ears cannot stand the constant scratching at the door. The chamber is sealed with magics cast in the ancient days by the morntai keepers in service to Larak, but they are centuries gone. From generation to generation my kin have kept vigil, not to keep the captive within, but to keep those that seek his release without. There are fewer of us in each generation. I fear one day we shall be no more, and what then?")
        PopulateLoreRecord(connection, LoreType2, "Breviary of Dom Pg76", "Each night my brothers an I pray earnestly to the three Gods in Grot, but the howls from the other side of the sealed door weaken our knees. We are taught that the seal cannot be undone without the reuniting of the shards, and the art of shardmending has been lost to time, we are told. Some of us are not so sure.")
        PopulateLoreRecord(connection, LoreType3, "Londo's Canticle Pg32", "The first of the shards has been found and awakened. Within it are held the powers of vanishing and reappearing. We have entrusted it to a younger brother for safe keeping. I can only hope our faith in him is well placed. It has dangerous sorcery within it.")
        PopulateLoreRecord(connection, LoreType4, "Tome of Krass Pg8", "Praise be to Reylon, Shyrana, and Larak, for saving the very life of our glorious leader with the power of the healing shard. It is a critical time for us, and without the reinforcement that the gods are with us, our brotherhood would fall away from its mission.")
        PopulateLoreRecord(connection, LoreType5, "Haikus of Esdjee #15", "Keep him in prison/for the one seeking his death/shall overtake all")
        PopulateLoreRecord(connection, LoreType6, "Bartulicas' Plea", "An answer must be found to banish Kordanor forever back to Jhama where he belongs. All efforts towards this have been meaningless vanity. An answer must exist and must be found, already we can feel the overpowerer approaching. We must not fail.")
        PopulateLoreRecord(connection, LoreType7, "Z's Epistle", "I have arrived. Yer time is nearly up. I cannot enter yer realm for your many wards of protection, but I will find a way to send another to fetch what I need. -Z")
        PopulateLoreRecord(connection, LoreType8, "Lore #8", "Lore #8")
        PopulateLoreRecord(connection, LoreType9, "Lore #9", "Lore #9")
        PopulateLoreRecord(connection, LoreType10, "Lore #10", "Lore #10")
        PopulateLoreRecord(connection, LoreType11, "Lore #11", "Lore #11")
        PopulateLoreRecord(connection, LoreType12, "Lore #12", "Lore #12")
        PopulateLoreRecord(connection, LoreType13, "Lore #13", "Lore #13")
        PopulateLoreRecord(connection, LoreType14, "Lore #14", "Lore #14")
        PopulateLoreRecord(connection, LoreType15, "Lore #15", "Lore #15")
        PopulateLoreRecord(connection, LoreType16, "Lore #16", "Lore #16")
        PopulateLoreRecord(connection, LoreType17, "Lore #17", "Lore #17")
        PopulateLoreRecord(connection, LoreType18, "Lore #18", "Lore #18")
        PopulateLoreRecord(connection, LoreType19, "Lore #19", "Lore #19")
        PopulateLoreRecord(connection, LoreType20, "Lore #20", "Lore #20")
        PopulateLoreRecord(connection, LoreType21, "Lore #21", "Lore #21")
        PopulateLoreRecord(connection, LoreType22, "Lore #22", "Lore #22")
        PopulateLoreRecord(connection, LoreType23, "Lore #23", "Lore #23")
        PopulateLoreRecord(connection, LoreType24, "Lore #24", "Lore #24")
        PopulateLoreRecord(connection, LoreType25, "Lore #25", "Lore #25")
    End Sub
    Private Sub PopulateLoreRecord(connection As SqliteConnection, loreId As Long, itemName As String, loreText As String)
        Using command = New SqliteCommand(
            $"INSERT INTO [{Tables.Lores}]
            (
                [{Columns.LoreIdColumn}], 
                [{Columns.ItemNameColumn}],
                [{Columns.LoreTextColumn}]
            ) 
            VALUES 
            (
                @{Columns.LoreIdColumn}, 
                @{Columns.ItemNameColumn}, 
                @{Columns.LoreTextColumn}
            );", connection)
            command.Parameters.AddWithValue($"@{Columns.LoreIdColumn}", loreId)
            command.Parameters.AddWithValue($"@{Columns.LoreTextColumn}", loreText)
            command.Parameters.AddWithValue($"@{Columns.ItemNameColumn}", itemName)
            command.ExecuteNonQuery()
        End Using
    End Sub
End Module
