Public Module CharacterTypePopulator
    Friend Const CharacterType1 = 1L
    Friend Const CharacterType2 = 2L
    Friend Const CharacterType3 = 3L
    Friend Const CharacterType4 = 4L
    Friend Const CharacterType5 = 5L
    Friend Const CharacterType6 = 6L
    Friend Const CharacterType7 = 7L
    Friend Const CharacterType8 = 8L
    Friend Const CharacterType9 = 9L
    Friend Const CharacterType10 = 10L
    Friend Const CharacterType11 = 11L
    Friend Const CharacterType12 = 12L
    Friend Const CharacterType13 = 13L
    Friend Const CharacterType14 = 14L
    Friend Const CharacterType15 = 15L
    Friend Const CharacterType16 = 16L
    Private Sub PopulateCharacterTypesRecord(connection As SqliteConnection, CharacterTypeId As Long, CharacterTypeName As String, XPValue As Long, MoneyDropDice As String, IsUndead As Long)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.CharacterTypes}]([{Columns.CharacterTypeIdColumn}], [{Columns.CharacterTypeNameColumn}], [{Columns.XPValueColumn}], [{Columns.MoneyDropDiceColumn}], [{Columns.IsUndeadColumn}]) VALUES (@{Columns.CharacterTypeIdColumn}, @{Columns.CharacterTypeNameColumn}, @{Columns.XPValueColumn}, @{Columns.MoneyDropDiceColumn}, @{Columns.IsUndeadColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.CharacterTypeIdColumn}", CharacterTypeId)
            command.Parameters.AddWithValue($"@{Columns.CharacterTypeNameColumn}", CharacterTypeName)
            command.Parameters.AddWithValue($"@{Columns.XPValueColumn}", XPValue)
            command.Parameters.AddWithValue($"@{Columns.MoneyDropDiceColumn}", MoneyDropDice)
            command.Parameters.AddWithValue($"@{Columns.IsUndeadColumn}", IsUndead)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Friend Sub PopulateCharacterTypes(connection As SqliteConnection)
        PopulateCharacterTypesRecord(connection, CharacterType1, "Acolyte", 5, "2d8", 0)
        PopulateCharacterTypesRecord(connection, CharacterType2, "Badger", 2, "0d1", 0)
        PopulateCharacterTypesRecord(connection, CharacterType3, "Bat", 1, "0d1", 0)
        PopulateCharacterTypesRecord(connection, CharacterType4, "Bishop", 5, "4d8", 0)
        PopulateCharacterTypesRecord(connection, CharacterType5, "Cabal Leader", 5, "5d8", 0)
        PopulateCharacterTypesRecord(connection, CharacterType6, "Goblin", 1, "2d6", 0)
        PopulateCharacterTypesRecord(connection, CharacterType7, "Goblin Elite", 2, "3d6", 0)
        PopulateCharacterTypesRecord(connection, CharacterType8, "Kordanor", 5, "0d1", 0)
        PopulateCharacterTypesRecord(connection, CharacterType9, "Malcontent", 2, "3d6", 0)
        PopulateCharacterTypesRecord(connection, CharacterType10, "MoonPerson", 3, "0d1", 0)
        PopulateCharacterTypesRecord(connection, CharacterType11, "N00b", 0, "0d1", 0)
        PopulateCharacterTypesRecord(connection, CharacterType12, "Priest", 5, "3d8", 0)
        PopulateCharacterTypesRecord(connection, CharacterType13, "Rat", 1, "0d1", 0)
        PopulateCharacterTypesRecord(connection, CharacterType14, "Skeleton", 1, "2d3", 1)
        PopulateCharacterTypesRecord(connection, CharacterType15, "Snake", 1, "0d1", 0)
        PopulateCharacterTypesRecord(connection, CharacterType16, "Zombie", 1, "2d4", 1)
    End Sub
    Private Sub PopulateCharacterTypeInitialStatisticsRecord(connection As SqliteConnection, CharacterTypeId As Long, CharacterStatisticTypeId As Long, InitialValue As Long)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.CharacterTypeInitialStatistics}]([{Columns.CharacterTypeIdColumn}], [{Columns.CharacterStatisticTypeIdColumn}], [{Columns.InitialValueColumn}]) VALUES (@{Columns.CharacterTypeIdColumn}, @{Columns.CharacterStatisticTypeIdColumn}, @{Columns.InitialValueColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.CharacterTypeIdColumn}", CharacterTypeId)
            command.Parameters.AddWithValue($"@{Columns.CharacterStatisticTypeIdColumn}", CharacterStatisticTypeId)
            command.Parameters.AddWithValue($"@{Columns.InitialValueColumn}", InitialValue)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Friend Sub PopulateCharacterTypeInitialStatistics(connection As SqliteConnection)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType1, 11, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType1, 1, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType1, 2, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType1, 6, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType1, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType1, 3, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType1, 7, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType1, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType1, 10, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType1, 4, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType1, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType2, 11, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType2, 1, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType2, 2, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType2, 6, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType2, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType2, 3, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType2, 7, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType2, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType2, 10, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType2, 4, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType2, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType3, 11, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType3, 1, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType3, 2, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType3, 6, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType3, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType3, 3, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType3, 7, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType3, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType3, 10, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType3, 4, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType3, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType4, 11, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType4, 1, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType4, 2, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType4, 6, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType4, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType4, 3, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType4, 7, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType4, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType4, 10, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType4, 4, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType4, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType5, 11, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType5, 1, 8)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType5, 2, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType5, 6, 5)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType5, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType5, 3, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType5, 7, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType5, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType5, 10, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType5, 4, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType5, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType6, 11, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType6, 1, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType6, 2, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType6, 6, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType6, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType6, 3, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType6, 7, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType6, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType6, 10, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType6, 4, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType6, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType7, 11, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType7, 1, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType7, 2, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType7, 6, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType7, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType7, 3, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType7, 7, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType7, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType7, 10, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType7, 4, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType7, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType8, 11, 5)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType8, 1, 8)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType8, 2, 5)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType8, 6, 10)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType8, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType8, 3, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType8, 7, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType8, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType8, 10, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType8, 4, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType8, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType9, 11, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType9, 1, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType9, 2, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType9, 6, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType9, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType9, 3, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType9, 7, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType9, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType9, 10, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType9, 4, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType9, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType10, 11, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType10, 1, 8)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType10, 2, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType10, 6, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType10, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType10, 3, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType10, 7, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType10, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType10, 10, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType10, 4, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType10, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 11, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 22, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 2, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 18, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 15, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 21, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 19, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 6, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 20, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 3, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 8, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 14, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 7, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 5, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 1, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 10, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 9, 8)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 4, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 16, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 17, 10)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 24, 50)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType11, 25, 10)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType12, 11, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType12, 1, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType12, 2, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType12, 6, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType12, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType12, 3, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType12, 7, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType12, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType12, 10, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType12, 4, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType12, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType13, 11, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType13, 1, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType13, 2, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType13, 6, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType13, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType13, 3, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType13, 7, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType13, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType13, 10, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType13, 4, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType13, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType14, 11, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType14, 1, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType14, 2, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType14, 6, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType14, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType14, 10, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType14, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType15, 11, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType15, 1, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType15, 2, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType15, 6, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType15, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType15, 3, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType15, 7, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType15, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType15, 10, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType15, 4, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType15, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType16, 11, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType16, 1, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType16, 2, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType16, 6, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType16, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType16, 10, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, CharacterType16, 12, 0)
    End Sub
    Private Sub PopulateCharacterTypeAttackTypesRecord(connection As SqliteConnection, CharacterTypeId As Long, AttackType As Long, Weight As Long)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.CharacterTypeAttackTypes}]([{Columns.CharacterTypeIdColumn}], [{Columns.AttackTypeColumn}], [{Columns.WeightColumn}]) VALUES (@{Columns.CharacterTypeIdColumn}, @{Columns.AttackTypeColumn}, @{Columns.WeightColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.CharacterTypeIdColumn}", CharacterTypeId)
            command.Parameters.AddWithValue($"@{Columns.AttackTypeColumn}", AttackType)
            command.Parameters.AddWithValue($"@{Columns.WeightColumn}", Weight)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Friend Sub PopulateCharacterTypeAttackTypes(connection As SqliteConnection)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType1, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType2, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType3, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType4, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType5, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType6, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType7, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType8, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType9, 1, 3)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType9, 2, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType10, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType11, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType12, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType13, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType14, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType15, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, CharacterType16, 1, 1)
    End Sub
End Module
