Friend Module ItemTypePopulator
    Friend Const ItemType1 = 1
    Friend Const ItemType2 = 2
    Friend Const ItemType3 = 3
    Friend Const ItemType4 = 4
    Friend Const ItemType5 = 5
    Friend Const ItemType6 = 6
    Friend Const ItemType7 = 7
    Friend Const ItemType8 = 8
    Friend Const ItemType9 = 9
    Friend Const ItemType10 = 10
    Friend Const ItemType11 = 11
    Friend Const ItemType12 = 12
    Friend Const ItemType13 = 13
    Friend Const ItemType14 = 14
    Friend Const ItemType15 = 15
    Friend Const ItemType16 = 16
    Friend Const ItemType17 = 17
    Friend Const ItemType18 = 18
    Friend Const ItemType19 = 19
    Friend Const ItemType20 = 20
    Friend Const ItemType21 = 21
    Friend Const ItemType22 = 22
    Friend Const ItemType23 = 23
    Friend Const ItemType24 = 24
    Friend Const ItemType25 = 25
    Friend Const ItemType26 = 26
    Friend Const ItemType27 = 27
    Friend Const ItemType28 = 28
    Friend Const ItemType29 = 29
    Friend Const ItemType30 = 30
    Friend Const ItemType31 = 31
    Friend Const ItemType32 = 32
    Friend Const ItemType33 = 33
    Friend Const ItemType34 = 34
    Friend Const ItemType35 = 35
    Friend Const ItemType36 = 36
    Friend Const ItemType37 = 37
    Friend Const ItemType38 = 38
    Friend Const ItemType39 = 39
    Friend Const ItemType40 = 40
    Friend Const ItemType41 = 41
    Friend Const ItemType42 = 42
    Friend Const ItemType43 = 43
    Friend Const ItemType44 = 44
    Friend Const ItemType45 = 45
    Friend Const ItemType46 = 46
    Friend Const ItemType47 = 47
    Friend Const ItemType48 = 48
    Friend Const ItemType49 = 49
    Friend Const ItemType50 = 50
    Friend Const ItemType51 = 51
    Friend Const ItemType52 = 52
    Friend Const ItemType53 = 53
    Private Sub PopulateItemTypesRecord(connection As SqliteConnection, ItemTypeId As Long, ItemTypeName As String, IsConsumed As Long)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypes}]([{Columns.ItemTypeIdColumn}], [{Columns.ItemTypeNameColumn}], [{Columns.IsConsumedColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.ItemTypeNameColumn}, @{Columns.IsConsumedColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeNameColumn}", ItemTypeName)
            command.Parameters.AddWithValue($"@{Columns.IsConsumedColumn}", IsConsumed)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Friend Sub PopulateItemTypes(connection As SqliteConnection)
        PopulateItemTypesRecord(connection, ItemType1, "FE Key", 1)
        PopulateItemTypesRecord(connection, ItemType2, "CU Key", 1)
        PopulateItemTypesRecord(connection, ItemType3, "AG Key", 1)
        PopulateItemTypesRecord(connection, ItemType4, "AU Key", 1)
        PopulateItemTypesRecord(connection, ItemType5, "PT Key", 1)
        PopulateItemTypesRecord(connection, ItemType6, "Elemental Orb", 0)
        PopulateItemTypesRecord(connection, ItemType7, "Potion", 1)
        PopulateItemTypesRecord(connection, ItemType8, "Goblin Ear", 1)
        PopulateItemTypesRecord(connection, ItemType9, "Skull Fragment", 1)
        PopulateItemTypesRecord(connection, ItemType10, "Dagger", 1)
        PopulateItemTypesRecord(connection, ItemType11, "Earth Shard", 0)
        PopulateItemTypesRecord(connection, ItemType12, "Water Shard", 0)
        PopulateItemTypesRecord(connection, ItemType13, "Fire Shard", 0)
        PopulateItemTypesRecord(connection, ItemType14, "Air Shard", 0)
        PopulateItemTypesRecord(connection, ItemType15, "Shield", 1)
        PopulateItemTypesRecord(connection, ItemType16, "Helmet", 1)
        PopulateItemTypesRecord(connection, ItemType17, "Chainmail", 1)
        PopulateItemTypesRecord(connection, ItemType18, "Shortsword", 1)
        PopulateItemTypesRecord(connection, ItemType19, "Brodesode", 1)
        PopulateItemTypesRecord(connection, ItemType20, "Platemail", 1)
        PopulateItemTypesRecord(connection, ItemType21, "Rat Tail", 1)
        PopulateItemTypesRecord(connection, ItemType22, "Holy ""Water""", 1)
        PopulateItemTypesRecord(connection, ItemType23, "Town Portal", 1)
        PopulateItemTypesRecord(connection, ItemType24, "kottbulle", 1)
        PopulateItemTypesRecord(connection, ItemType25, "Magic Egg", 1)
        PopulateItemTypesRecord(connection, ItemType26, "Beer", 1)
        PopulateItemTypesRecord(connection, ItemType27, "Trousers", 1)
        PopulateItemTypesRecord(connection, ItemType28, "Pr0n Scroll", 1)
        PopulateItemTypesRecord(connection, ItemType29, "Moon Portal", 1)
        PopulateItemTypesRecord(connection, ItemType30, "Empty Bottle", 1)
        PopulateItemTypesRecord(connection, ItemType31, "Book of Holy Bolt", 1)
        PopulateItemTypesRecord(connection, ItemType32, "Membership Card", 1)
        PopulateItemTypesRecord(connection, ItemType33, "Bong", 1)
        PopulateItemTypesRecord(connection, ItemType34, """Herb""", 1)
        PopulateItemTypesRecord(connection, ItemType35, "kottbulle", 1)
        PopulateItemTypesRecord(connection, ItemType36, "Mushroom", 1)
        PopulateItemTypesRecord(connection, ItemType37, "Rotten Egg", 1)
        PopulateItemTypesRecord(connection, ItemType38, "Zombie Taint", 1)
        PopulateItemTypesRecord(connection, ItemType39, "Lotion", 1)
        PopulateItemTypesRecord(connection, ItemType40, "Bat Wing", 1)
        PopulateItemTypesRecord(connection, ItemType41, "Snake Fang", 1)
        PopulateItemTypesRecord(connection, ItemType42, "Shoe Laces", 1)
        PopulateItemTypesRecord(connection, ItemType43, "Spacesord", 1)
        PopulateItemTypesRecord(connection, ItemType44, "Horns of Kordanor", 1)
        PopulateItemTypesRecord(connection, ItemType45, "Amulet of HP", 1)
        PopulateItemTypesRecord(connection, ItemType46, "Ring of HP", 1)
        PopulateItemTypesRecord(connection, ItemType47, "Book of Purify", 1)
        PopulateItemTypesRecord(connection, ItemType48, "Amulet of STR", 1)
        PopulateItemTypesRecord(connection, ItemType49, "Amulet of DEX", 1)
        PopulateItemTypesRecord(connection, ItemType50, "Amulet of POW", 1)
        PopulateItemTypesRecord(connection, ItemType51, "Amulet of Mana", 1)
        PopulateItemTypesRecord(connection, ItemType52, "Amulet of Yendor", 1)
        PopulateItemTypesRecord(connection, ItemType53, "Scroll", 0)
    End Sub
    Private Sub PopulateItemTypeShopTypesRecord(connection As SqliteConnection, ItemTypeId As Long, ShoppeTypeId As Long, TransactionTypeId As Long)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypeShopTypes}]([{Columns.ItemTypeIdColumn}], [{Columns.ShoppeTypeIdColumn}], [{Columns.TransactionTypeIdColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.ShoppeTypeIdColumn}, @{Columns.TransactionTypeIdColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.ShoppeTypeIdColumn}", ShoppeTypeId)
            command.Parameters.AddWithValue($"@{Columns.TransactionTypeIdColumn}", TransactionTypeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Friend Const TransactionTypeOffer = 1L
    Friend Const TransactionTypePrice = 2L
    Friend Const TransactionTypeRepair = 3L
    Sub PopulateItemTypeShopTypes(connection As SqliteConnection)
        PopulateItemTypeShopTypesRecord(connection, ItemType7, ShoppeType4, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType8, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType9, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType10, ShoppeType2, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType10, ShoppeType2, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType10, ShoppeType2, TransactionTypeRepair)
        PopulateItemTypeShopTypesRecord(connection, ItemType15, ShoppeType2, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType15, ShoppeType2, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType15, ShoppeType2, TransactionTypeRepair)
        PopulateItemTypeShopTypesRecord(connection, ItemType16, ShoppeType2, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType16, ShoppeType2, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType16, ShoppeType2, TransactionTypeRepair)
        PopulateItemTypeShopTypesRecord(connection, ItemType17, ShoppeType2, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType17, ShoppeType2, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType17, ShoppeType2, TransactionTypeRepair)
        PopulateItemTypeShopTypesRecord(connection, ItemType18, ShoppeType2, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType18, ShoppeType2, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType18, ShoppeType2, TransactionTypeRepair)
        PopulateItemTypeShopTypesRecord(connection, ItemType19, ShoppeType2, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType19, ShoppeType2, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType29, ShoppeType2, TransactionTypeRepair)
        PopulateItemTypeShopTypesRecord(connection, ItemType20, ShoppeType2, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType20, ShoppeType2, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType20, ShoppeType2, TransactionTypeRepair)
        PopulateItemTypeShopTypesRecord(connection, ItemType21, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType22, ShoppeType4, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType23, ShoppeType1, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType24, ShoppeType3, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType25, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType26, ShoppeType3, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType27, ShoppeType5, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType28, ShoppeType5, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType29, ShoppeType1, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType31, ShoppeType1, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType33, ShoppeType1, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType34, ShoppeType1, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType36, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType38, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType39, ShoppeType5, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType40, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType41, ShoppeType1, TransactionTypeOffer)
        PopulateItemTypeShopTypesRecord(connection, ItemType47, ShoppeType1, TransactionTypePrice)
        PopulateItemTypeShopTypesRecord(connection, ItemType52, ShoppeType5, TransactionTypePrice)
    End Sub
    Sub PopulateItemTypeEventsRecord(connection As SqliteConnection, ItemTypeId As Long, EventId As Long, EventName As String)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypeEvents}]([{Columns.ItemTypeIdColumn}], [{Columns.EventIdColumn}], [{Columns.EventNameColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.EventIdColumn}, @{Columns.EventNameColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.EventIdColumn}", EventId)
            command.Parameters.AddWithValue($"@{Columns.EventNameColumn}", EventName)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Friend Const EventTypePurify = 1
    Friend Const EventTypeCanUse = 2
    Friend Const EventTypeUse = 3
    Friend Const EventTypeDecay = 4
    Sub PopulateItemTypeEvents(connection As SqliteConnection)
        PopulateItemTypeEventsRecord(connection, ItemType7, EventTypeCanUse, "AlwaysTrue")
        PopulateItemTypeEventsRecord(connection, ItemType7, EventTypeUse, "DrinkPotion")
        PopulateItemTypeEventsRecord(connection, ItemType11, EventTypeCanUse, "CanUseEarthShard")
        PopulateItemTypeEventsRecord(connection, ItemType11, EventTypeUse, "UseEarthShard")
        PopulateItemTypeEventsRecord(connection, ItemType12, EventTypeCanUse, "CanUseWaterShard")
        PopulateItemTypeEventsRecord(connection, ItemType12, EventTypeUse, "UseWaterShard")
        PopulateItemTypeEventsRecord(connection, ItemType13, EventTypeCanUse, "CanUseFireShard")
        PopulateItemTypeEventsRecord(connection, ItemType13, EventTypeUse, "UseFireShard")
        PopulateItemTypeEventsRecord(connection, ItemType14, EventTypeCanUse, "CanUseAirShard")
        PopulateItemTypeEventsRecord(connection, ItemType14, EventTypeUse, "UseAirShard")
        PopulateItemTypeEventsRecord(connection, ItemType22, EventTypeCanUse, "IsFightingUndead")
        PopulateItemTypeEventsRecord(connection, ItemType22, EventTypeUse, "UseHolyWater")
        PopulateItemTypeEventsRecord(connection, ItemType23, EventTypeCanUse, "IsInDungeon")
        PopulateItemTypeEventsRecord(connection, ItemType23, EventTypeUse, "UseTownPortal")
        PopulateItemTypeEventsRecord(connection, ItemType24, EventTypeCanUse, "AlwaysTrue")
        PopulateItemTypeEventsRecord(connection, ItemType24, EventTypeUse, "EatFood")
        PopulateItemTypeEventsRecord(connection, ItemType25, EventTypeCanUse, "AlwaysTrue")
        PopulateItemTypeEventsRecord(connection, ItemType25, EventTypeUse, "UseMagicEgg")
        PopulateItemTypeEventsRecord(connection, ItemType26, EventTypeCanUse, "CanUseBeer")
        PopulateItemTypeEventsRecord(connection, ItemType26, EventTypeUse, "UseBeer")
        PopulateItemTypeEventsRecord(connection, ItemType28, EventTypeCanUse, "CanUsePr0n")
        PopulateItemTypeEventsRecord(connection, ItemType28, EventTypeUse, "UsePr0n")
        PopulateItemTypeEventsRecord(connection, ItemType29, EventTypeCanUse, "IsInDungeon")
        PopulateItemTypeEventsRecord(connection, ItemType29, EventTypeUse, "UseMoonPortal")
        PopulateItemTypeEventsRecord(connection, ItemType30, EventTypeCanUse, "CanUseBottle")
        PopulateItemTypeEventsRecord(connection, ItemType30, EventTypeUse, "UseBottle")
        PopulateItemTypeEventsRecord(connection, ItemType31, EventTypeCanUse, "CanLearnHolyBolt")
        PopulateItemTypeEventsRecord(connection, ItemType31, EventTypeUse, "LearnHolyBolt")
        PopulateItemTypeEventsRecord(connection, ItemType34, EventTypeCanUse, "HasBong")
        PopulateItemTypeEventsRecord(connection, ItemType34, EventTypeUse, "UseHerb")
        PopulateItemTypeEventsRecord(connection, ItemType35, EventTypePurify, "PurifyFood")
        PopulateItemTypeEventsRecord(connection, ItemType35, EventTypeCanUse, "AlwaysTrue")
        PopulateItemTypeEventsRecord(connection, ItemType35, EventTypeUse, "UseRottenFood")
        PopulateItemTypeEventsRecord(connection, ItemType37, EventTypeCanUse, "CanUseRottenEgg")
        PopulateItemTypeEventsRecord(connection, ItemType37, EventTypeUse, "UseRottenEgg")
        PopulateItemTypeEventsRecord(connection, ItemType47, EventTypeCanUse, "CanLearnPurify")
        PopulateItemTypeEventsRecord(connection, ItemType47, EventTypeUse, "LearnPurify")
        PopulateItemTypeEventsRecord(connection, ItemType24, EventTypeDecay, "FoodDecay")
        PopulateItemTypeEventsRecord(connection, ItemType35, EventTypeDecay, "RottenFoodDecay")
        PopulateItemTypeEventsRecord(connection, ItemType53, EventTypeCanUse, "AlwaysTrue")
        PopulateItemTypeEventsRecord(connection, ItemType53, EventTypeUse, "ReadScroll")
    End Sub
    Private Sub PopulateItemTypeEquipSlotsRecord(connection As SqliteConnection, ItemTypeId As Long, EquipSlotId As Long)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypeEquipSlots}]([{Columns.ItemTypeIdColumn}], [{Columns.EquipSlotIdColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.EquipSlotIdColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.EquipSlotIdColumn}", EquipSlotId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Friend Sub PopulateItemTypeEquipSlots(connection As SqliteConnection)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType10, EquipSlot1)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType15, EquipSlot2)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType16, EquipSlot3)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType17, EquipSlot4)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType18, EquipSlot1)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType19, EquipSlot1)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType20, EquipSlot4)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType27, EquipSlot5)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType30, EquipSlot1)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType43, EquipSlot1)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType45, EquipSlot6)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType46, EquipSlot7)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType46, EquipSlot8)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType48, EquipSlot6)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType49, EquipSlot6)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType50, EquipSlot6)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType51, EquipSlot6)
        PopulateItemTypeEquipSlotsRecord(connection, ItemType52, EquipSlot6)
    End Sub
    Sub PopulateItemTypeSpawnCountsRecord(connection As SqliteConnection, ItemTypeId As Long, DungeonLevelId As Long, SpawnDice As String)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypeSpawnCounts}]([{Columns.ItemTypeIdColumn}], [{Columns.DungeonLevelIdColumn}], [{Columns.SpawnDiceColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.DungeonLevelIdColumn}, @{Columns.SpawnDiceColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.DungeonLevelIdColumn}", DungeonLevelId)
            command.Parameters.AddWithValue($"@{Columns.SpawnDiceColumn}", SpawnDice)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypeSpawnCounts(connection As SqliteConnection)
        PopulateItemTypeSpawnCountsRecord(connection, ItemType7, DungeonLevel1, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType7, DungeonLevel2, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType7, DungeonLevel3, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType7, DungeonLevel4, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType7, DungeonLevel5, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType10, DungeonLevel1, "4d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType10, DungeonLevel2, "2d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType11, DungeonLevel2, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType12, DungeonLevel4, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType13, DungeonLevel3, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType14, DungeonLevel1, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType15, DungeonLevel1, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType16, DungeonLevel1, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType17, DungeonLevel1, "1d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType18, DungeonLevel1, "2d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType18, DungeonLevel2, "1d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType19, DungeonLevel2, "2d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType19, DungeonLevel3, "1d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType20, DungeonLevel2, "1d6")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType43, DungeonLevel6, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType45, DungeonLevel1, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType48, DungeonLevel4, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType50, DungeonLevel3, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType51, DungeonLevel5, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType5, DungeonLevel1, "5d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType5, DungeonLevel2, "5d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType5, DungeonLevel3, "5d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType5, DungeonLevel4, "5d1")
        PopulateItemTypeSpawnCountsRecord(connection, ItemType5, DungeonLevel5, "5d1")
    End Sub
    Sub PopulateItemTypeSpawnLocationTypesRecord(connection As SqliteConnection, ItemTypeId As Long, DungeonLevelId As Long, LocationTypeId As Long)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypeSpawnLocationTypes}]([{Columns.ItemTypeIdColumn}], [{Columns.DungeonLevelIdColumn}], [{Columns.LocationTypeIdColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.DungeonLevelIdColumn}, @{Columns.LocationTypeIdColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.DungeonLevelIdColumn}", DungeonLevelId)
            command.Parameters.AddWithValue($"@{Columns.LocationTypeIdColumn}", LocationTypeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypeSpawnLocationTypes(connection As SqliteConnection)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType1, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType1, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType1, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType1, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType1, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType2, DungeonLevel1, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType3, DungeonLevel2, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType4, DungeonLevel3, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType5, DungeonLevel4, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel1, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel2, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel3, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel4, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType7, DungeonLevel5, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType10, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType10, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType10, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType10, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType10, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType11, DungeonLevel2, LocationType6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType12, DungeonLevel4, LocationType6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType14, DungeonLevel1, LocationType6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel1, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel2, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel3, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel4, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType15, DungeonLevel5, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel1, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel2, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel3, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel4, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType16, DungeonLevel5, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel1, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel2, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel3, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel4, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel5, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType17, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType18, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType18, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType18, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType18, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType18, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType19, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType19, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType19, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType19, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType19, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType20, DungeonLevel2, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType20, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType20, DungeonLevel3, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType20, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType20, DungeonLevel4, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType20, DungeonLevel5, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType20, DungeonLevel5, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType43, DungeonLevel6, LocationType8)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType45, DungeonLevel1, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType45, DungeonLevel1, LocationType6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType48, DungeonLevel4, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType48, DungeonLevel4, LocationType6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType50, DungeonLevel3, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType50, DungeonLevel3, LocationType6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType51, DungeonLevel2, LocationType5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType51, DungeonLevel2, LocationType6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType53, DungeonLevel1, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType53, DungeonLevel2, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType53, DungeonLevel3, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType53, DungeonLevel4, LocationType4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, ItemType53, DungeonLevel5, LocationType4)
    End Sub
    Sub PopulateItemTypeCharacterStatisticBuffsRecord(connection As SqliteConnection, ItemTypeId As Long, CharacterStatisticTypeId As Long, Buff As Long)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypeCharacterStatisticBuffs}]([{Columns.ItemTypeIdColumn}], [{Columns.CharacterStatisticTypeIdColumn}], [{Columns.BuffColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.CharacterStatisticTypeIdColumn}, @{Columns.BuffColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.CharacterStatisticTypeIdColumn}", CharacterStatisticTypeId)
            command.Parameters.AddWithValue($"@{Columns.BuffColumn}", Buff)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypeCharacterStatisticBuffs(connection As SqliteConnection)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, ItemType45, CharacterStatisticType6, 1)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, ItemType46, CharacterStatisticType6, 1)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, ItemType49, CharacterStatisticType2, 1)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, ItemType50, CharacterStatisticType5, 1)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, ItemType51, CharacterStatisticType8, 1)
    End Sub
    Private Sub PopulateItemTypeStatisticsRecord(connection As SqliteConnection, ItemTypeId As Long, ItemTypeStatisticTypeId As Long, ItemTypeStatisticValue As Long)
        Using command = New SqliteCommand($"INSERT INTO [{Tables.ItemTypeStatistics}]([{Columns.ItemTypeIdColumn}], [{Columns.ItemTypeStatisticTypeIdColumn}], [{Columns.ItemTypeStatisticValueColumn}]) VALUES (@{Columns.ItemTypeIdColumn}, @{Columns.ItemTypeStatisticTypeIdColumn}, @{Columns.ItemTypeStatisticValueColumn});", connection)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeIdColumn}", ItemTypeId)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeStatisticTypeIdColumn}", ItemTypeStatisticTypeId)
            command.Parameters.AddWithValue($"@{Columns.ItemTypeStatisticValueColumn}", ItemTypeStatisticValue)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Friend Sub PopulateItemTypeStatistics(connection As SqliteConnection)
        PopulateItemTypeStatisticsRecord(connection, ItemType7, ItemTypeStatisticType1, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType7, ItemTypeStatisticType7, 15)
        PopulateItemTypeStatisticsRecord(connection, ItemType8, ItemTypeStatisticType6, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType9, ItemTypeStatisticType6, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, ItemTypeStatisticType1, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, ItemTypeStatisticType2, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, ItemTypeStatisticType3, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, ItemTypeStatisticType5, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, ItemTypeStatisticType6, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, ItemTypeStatisticType7, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType10, ItemTypeStatisticType8, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType15, ItemTypeStatisticType1, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType15, ItemTypeStatisticType4, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType15, ItemTypeStatisticType5, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType15, ItemTypeStatisticType6, 3)
        PopulateItemTypeStatisticsRecord(connection, ItemType15, ItemTypeStatisticType7, 15)
        PopulateItemTypeStatisticsRecord(connection, ItemType15, ItemTypeStatisticType8, 6)
        PopulateItemTypeStatisticsRecord(connection, ItemType16, ItemTypeStatisticType1, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType16, ItemTypeStatisticType4, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType16, ItemTypeStatisticType5, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType16, ItemTypeStatisticType6, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType16, ItemTypeStatisticType7, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType16, ItemTypeStatisticType8, 4)
        PopulateItemTypeStatisticsRecord(connection, ItemType17, ItemTypeStatisticType1, 20)
        PopulateItemTypeStatisticsRecord(connection, ItemType17, ItemTypeStatisticType3, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType17, ItemTypeStatisticType4, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType17, ItemTypeStatisticType6, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType17, ItemTypeStatisticType7, 50)
        PopulateItemTypeStatisticsRecord(connection, ItemType17, ItemTypeStatisticType8, 20)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, ItemTypeStatisticType1, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, ItemTypeStatisticType3, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, ItemTypeStatisticType2, 4)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, ItemTypeStatisticType5, 20)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, ItemTypeStatisticType6, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, ItemTypeStatisticType7, 25)
        PopulateItemTypeStatisticsRecord(connection, ItemType18, ItemTypeStatisticType8, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, ItemTypeStatisticType1, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, ItemTypeStatisticType2, 6)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, ItemTypeStatisticType3, 3)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, ItemTypeStatisticType5, 40)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, ItemTypeStatisticType6, 20)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, ItemTypeStatisticType7, 100)
        PopulateItemTypeStatisticsRecord(connection, ItemType19, ItemTypeStatisticType8, 40)
        PopulateItemTypeStatisticsRecord(connection, ItemType20, ItemTypeStatisticType1, 40)
        PopulateItemTypeStatisticsRecord(connection, ItemType20, ItemTypeStatisticType4, 4)
        PopulateItemTypeStatisticsRecord(connection, ItemType20, ItemTypeStatisticType5, 50)
        PopulateItemTypeStatisticsRecord(connection, ItemType20, ItemTypeStatisticType6, 50)
        PopulateItemTypeStatisticsRecord(connection, ItemType20, ItemTypeStatisticType7, 250)
        PopulateItemTypeStatisticsRecord(connection, ItemType20, ItemTypeStatisticType8, 100)
        PopulateItemTypeStatisticsRecord(connection, ItemType21, ItemTypeStatisticType6, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType22, ItemTypeStatisticType7, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType23, ItemTypeStatisticType7, 50)
        PopulateItemTypeStatisticsRecord(connection, ItemType24, ItemTypeStatisticType7, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType25, ItemTypeStatisticType6, 100)
        PopulateItemTypeStatisticsRecord(connection, ItemType26, ItemTypeStatisticType1, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType26, ItemTypeStatisticType7, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType27, ItemTypeStatisticType7, 100)
        PopulateItemTypeStatisticsRecord(connection, ItemType28, ItemTypeStatisticType7, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType29, ItemTypeStatisticType7, 5000)
        PopulateItemTypeStatisticsRecord(connection, ItemType30, ItemTypeStatisticType1, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType30, ItemTypeStatisticType2, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType30, ItemTypeStatisticType3, 1)
        PopulateItemTypeStatisticsRecord(connection, ItemType30, ItemTypeStatisticType5, 3)
        PopulateItemTypeStatisticsRecord(connection, ItemType31, ItemTypeStatisticType7, 100)
        PopulateItemTypeStatisticsRecord(connection, ItemType32, ItemTypeStatisticType6, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType33, ItemTypeStatisticType7, 25)
        PopulateItemTypeStatisticsRecord(connection, ItemType34, ItemTypeStatisticType7, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType36, ItemTypeStatisticType6, 25)
        PopulateItemTypeStatisticsRecord(connection, ItemType38, ItemTypeStatisticType6, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType39, ItemTypeStatisticType1, 2)
        PopulateItemTypeStatisticsRecord(connection, ItemType39, ItemTypeStatisticType6, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType39, ItemTypeStatisticType7, 25)
        PopulateItemTypeStatisticsRecord(connection, ItemType40, ItemTypeStatisticType6, 3)
        PopulateItemTypeStatisticsRecord(connection, ItemType41, ItemTypeStatisticType6, 3)
        PopulateItemTypeStatisticsRecord(connection, ItemType43, ItemTypeStatisticType1, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType43, ItemTypeStatisticType3, 10)
        PopulateItemTypeStatisticsRecord(connection, ItemType43, ItemTypeStatisticType4, 5)
        PopulateItemTypeStatisticsRecord(connection, ItemType43, ItemTypeStatisticType6, 100)
        PopulateItemTypeStatisticsRecord(connection, ItemType47, ItemTypeStatisticType7, 50)
        PopulateItemTypeStatisticsRecord(connection, ItemType52, ItemTypeStatisticType7, 1000)
    End Sub
End Module
