Public Module Populate
    Sub Populate(connection As SqliteConnection)
        PopulateCharacterTypes(connection)
        PopulateCharacterStatisticTypes(connection)
        PopulateCharacterTypeInitialStatistics(connection)
        PopulateCharacterTypeAttackTypes(connection)
        PopulateItemTypes(connection)
        PopulateCharacterTypeBribes(connection)
        PopulateCharacterTypeEnemies(connection)
        PopulateCharacterTypeLoots(connection)
        PopulateCharacterTypePartingShots(connection)
        PopulateDungeonLevels(connection)
        PopulateCharacterTypeSpawnCounts(connection)
        PopulateLocationTypes(connection)
        PopulateCharacterTypeSpawnLocations(connection)
        PopulateEquipSlots(connection)
        PopulateQuestTypes(connection)
        PopulateItemStatisticTypes(connection)
        PopulateItemTypeEquipSlots(connection)
        PopulateItemTypeEvents(connection)
        PopulateShoppeTypes(connection)
        PopulateItemTypeShopTypes(connection)
        PopulateItemTypeSpawnCounts(connection)
        PopulateItemTypeSpawnLocationTypes(connection)
        PopulateItemTypeCharacterStatisticBuffs(connection)
        PopulateItemTypeStatisticTypes(connection)
        PopulateItemTypeStatistics(connection)
        PopulateFeatureTypes(connection)
        PopulateDirections(connection)
        PopulateRouteTypes(connection)
        PopulateRouteTypeLocks(connection)
        PopulateSpellTypes(connection)
        PopulateSpellTypeRequiredPowers(connection)
        PopulateLocations(connection)
        PopulateCharacters(connection)
        PopulateCharacterLocations(connection)
        PopulateCharacterSpells(connection)
        PopulatePlayers(connection)
        PopulateItems(connection)
        PopulateCharacterEquipSlots(connection)
        PopulateCharacterQuestCompletions(connection)
        PopulateCharacterQuests(connection)
        PopulateCharacterStatistics(connection)
        PopulateInventories(connection)
        PopulateInventoryItems(connection)
        PopulateItemStatistics(connection)
        PopulateLocationDungeonLevels(connection)
        PopulateFeatures(connection)
        PopulateLocationStatistics(connection)
        PopulateRoutes(connection)
    End Sub
    Sub PopulateCharacterTypesRecord(connection As SqliteConnection, CharacterTypeId As Long, CharacterTypeName As String, XPValue As Long, MoneyDropDice As String, IsUndead As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterTypes]([CharacterTypeId], [CharacterTypeName], [XPValue], [MoneyDropDice], [IsUndead]) VALUES (@CharacterTypeId, @CharacterTypeName, @XPValue, @MoneyDropDice, @IsUndead);", connection)
            command.Parameters.AddWithValue("@CharacterTypeId", CharacterTypeId)
            command.Parameters.AddWithValue("@CharacterTypeName", CharacterTypeName)
            command.Parameters.AddWithValue("@XPValue", XPValue)
            command.Parameters.AddWithValue("@MoneyDropDice", MoneyDropDice)
            command.Parameters.AddWithValue("@IsUndead", IsUndead)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterTypes(connection As SqliteConnection)
        PopulateCharacterTypesRecord(connection, 1, "Acolyte", 5, "2d8", 0)
        PopulateCharacterTypesRecord(connection, 2, "Badger", 2, "0d1", 0)
        PopulateCharacterTypesRecord(connection, 3, "Bat", 1, "0d1", 0)
        PopulateCharacterTypesRecord(connection, 4, "Bishop", 5, "4d8", 0)
        PopulateCharacterTypesRecord(connection, 5, "Cabal Leader", 5, "5d8", 0)
        PopulateCharacterTypesRecord(connection, 6, "Goblin", 1, "2d6", 0)
        PopulateCharacterTypesRecord(connection, 7, "Goblin Elite", 2, "3d6", 0)
        PopulateCharacterTypesRecord(connection, 8, "Kordanor", 5, "0d1", 0)
        PopulateCharacterTypesRecord(connection, 9, "Malcontent", 2, "3d6", 0)
        PopulateCharacterTypesRecord(connection, 10, "MoonPerson", 3, "0d1", 0)
        PopulateCharacterTypesRecord(connection, 11, "N00b", 0, "0d1", 0)
        PopulateCharacterTypesRecord(connection, 12, "Priest", 5, "3d8", 0)
        PopulateCharacterTypesRecord(connection, 13, "Rat", 1, "0d1", 0)
        PopulateCharacterTypesRecord(connection, 14, "Skeleton", 1, "2d3", 1)
        PopulateCharacterTypesRecord(connection, 15, "Snake", 1, "0d1", 0)
        PopulateCharacterTypesRecord(connection, 16, "Zombie", 1, "2d4", 1)
    End Sub
    Sub PopulateCharacterStatisticTypesRecord(connection As SqliteConnection, CharacterStatisticTypeId As Long, CharacterStatisticTypeName As String, Abbreviation As String, MinimumValue As Long, DefaultValue As Long?, MaximumValue As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterStatisticTypes]([CharacterStatisticTypeId], [CharacterStatisticTypeName], [Abbreviation], [MinimumValue], [DefaultValue], [MaximumValue]) VALUES (@CharacterStatisticTypeId, @CharacterStatisticTypeName, @Abbreviation, @MinimumValue, @DefaultValue, @MaximumValue);", connection)
            command.Parameters.AddWithValue("@CharacterStatisticTypeId", CharacterStatisticTypeId)
            command.Parameters.AddWithValue("@CharacterStatisticTypeName", CharacterStatisticTypeName)
            command.Parameters.AddWithValue("@Abbreviation", Abbreviation)
            command.Parameters.AddWithValue("@MinimumValue", MinimumValue)
            command.Parameters.AddWithValue("@DefaultValue", If(DefaultValue Is Nothing, CObj(DBNull.Value), DefaultValue))
            command.Parameters.AddWithValue("@MaximumValue", MaximumValue)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterStatisticTypes(connection As SqliteConnection)
        PopulateCharacterStatisticTypesRecord(connection, 1, "Strength", "STR", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 2, "Dexterity", "DEX", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 3, "Influence", "INF", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 4, "Willpower", "WIL", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 5, "Power", "POW", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 6, "HP", "HP", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 7, "MP", "MP", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 8, "Mana", "Mana", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 9, "Unassigned", "Unassigned", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 10, "Unarmed Maximum Damage", "MAXDMG", 0, 1, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 11, "Base Maximum Defend", "MAXDEF", 0, 1, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 12, "Wounds", "Wounds", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 13, "Stress", "Stress", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 14, "Money", "$", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 15, "Fatigue", "Fatigue", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 16, "XP", "XP", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 17, "XP Goal", "XP Goal", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 18, "Drunkenness", "Drunkenness", 0, 0, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 19, "Highness", "Highness", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 20, "Hunger", "Hunger", 0, 0, 100)
        PopulateCharacterStatisticTypesRecord(connection, 21, "Food Poisoning", "Food Poisoning", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 22, "Chafing", "Chafing", 0, 0, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 23, "Immobilization", "Immobilization", 0, Nothing, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 24, "Base Lift", "Base Lift", 0, 0, 99999)
        PopulateCharacterStatisticTypesRecord(connection, 25, "Bonus Lift", "Bonus Lift", 0, 0, 99999)
    End Sub
    Sub PopulateCharacterTypeInitialStatisticsRecord(connection As SqliteConnection, CharacterTypeId As Long, CharacterStatisticTypeId As Long, InitialValue As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterTypeInitialStatistics]([CharacterTypeId], [CharacterStatisticTypeId], [InitialValue]) VALUES (@CharacterTypeId, @CharacterStatisticTypeId, @InitialValue);", connection)
            command.Parameters.AddWithValue("@CharacterTypeId", CharacterTypeId)
            command.Parameters.AddWithValue("@CharacterStatisticTypeId", CharacterStatisticTypeId)
            command.Parameters.AddWithValue("@InitialValue", InitialValue)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterTypeInitialStatistics(connection As SqliteConnection)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 1, 11, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 1, 1, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 1, 2, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 1, 6, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 1, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 1, 3, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 1, 7, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 1, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 1, 10, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 1, 4, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 1, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 2, 11, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 2, 1, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 2, 2, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 2, 6, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 2, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 2, 3, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 2, 7, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 2, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 2, 10, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 2, 4, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 2, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 3, 11, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 3, 1, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 3, 2, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 3, 6, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 3, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 3, 3, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 3, 7, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 3, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 3, 10, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 3, 4, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 3, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 4, 11, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 4, 1, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 4, 2, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 4, 6, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 4, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 4, 3, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 4, 7, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 4, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 4, 10, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 4, 4, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 4, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 5, 11, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 5, 1, 8)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 5, 2, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 5, 6, 5)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 5, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 5, 3, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 5, 7, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 5, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 5, 10, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 5, 4, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 5, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 6, 11, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 6, 1, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 6, 2, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 6, 6, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 6, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 6, 3, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 6, 7, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 6, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 6, 10, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 6, 4, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 6, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 7, 11, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 7, 1, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 7, 2, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 7, 6, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 7, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 7, 3, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 7, 7, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 7, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 7, 10, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 7, 4, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 7, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 8, 11, 5)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 8, 1, 8)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 8, 2, 5)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 8, 6, 10)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 8, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 8, 3, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 8, 7, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 8, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 8, 10, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 8, 4, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 8, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 9, 11, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 9, 1, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 9, 2, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 9, 6, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 9, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 9, 3, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 9, 7, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 9, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 9, 10, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 9, 4, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 9, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 10, 11, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 10, 1, 8)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 10, 2, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 10, 6, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 10, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 10, 3, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 10, 7, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 10, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 10, 10, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 10, 4, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 10, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 11, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 22, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 2, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 18, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 15, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 21, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 19, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 6, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 20, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 3, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 8, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 14, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 7, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 5, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 1, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 10, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 9, 8)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 4, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 16, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 17, 10)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 24, 50)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 11, 25, 10)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 12, 11, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 12, 1, 6)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 12, 2, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 12, 6, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 12, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 12, 3, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 12, 7, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 12, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 12, 10, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 12, 4, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 12, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 13, 11, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 13, 1, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 13, 2, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 13, 6, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 13, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 13, 3, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 13, 7, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 13, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 13, 10, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 13, 4, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 13, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 14, 11, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 14, 1, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 14, 2, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 14, 6, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 14, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 14, 10, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 14, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 15, 11, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 15, 1, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 15, 2, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 15, 6, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 15, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 15, 3, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 15, 7, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 15, 13, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 15, 10, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 15, 4, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 15, 12, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 16, 11, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 16, 1, 4)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 16, 2, 3)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 16, 6, 1)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 16, 23, 0)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 16, 10, 2)
        PopulateCharacterTypeInitialStatisticsRecord(connection, 16, 12, 0)
    End Sub
    Sub PopulateCharacterTypeAttackTypesRecord(connection As SqliteConnection, CharacterTypeId As Long, AttackType As Long, Weight As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterTypeAttackTypes]([CharacterTypeId], [AttackType], [Weight]) VALUES (@CharacterTypeId, @AttackType, @Weight);", connection)
            command.Parameters.AddWithValue("@CharacterTypeId", CharacterTypeId)
            command.Parameters.AddWithValue("@AttackType", AttackType)
            command.Parameters.AddWithValue("@Weight", Weight)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterTypeAttackTypes(connection As SqliteConnection)
        PopulateCharacterTypeAttackTypesRecord(connection, 1, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 2, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 3, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 4, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 5, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 6, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 7, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 8, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 9, 1, 3)
        PopulateCharacterTypeAttackTypesRecord(connection, 9, 2, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 10, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 11, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 12, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 13, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 14, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 15, 1, 1)
        PopulateCharacterTypeAttackTypesRecord(connection, 16, 1, 1)
    End Sub
    Sub PopulateItemTypesRecord(connection As SqliteConnection, ItemTypeId As Long, ItemTypeName As String, IsConsumed As Long)
        Using command = New SqliteCommand("INSERT INTO [ItemTypes]([ItemTypeId], [ItemTypeName], [IsConsumed]) VALUES (@ItemTypeId, @ItemTypeName, @IsConsumed);", connection)
            command.Parameters.AddWithValue("@ItemTypeId", ItemTypeId)
            command.Parameters.AddWithValue("@ItemTypeName", ItemTypeName)
            command.Parameters.AddWithValue("@IsConsumed", IsConsumed)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypes(connection As SqliteConnection)
        PopulateItemTypesRecord(connection, 1, "FE Key", 1)
        PopulateItemTypesRecord(connection, 2, "CU Key", 1)
        PopulateItemTypesRecord(connection, 3, "AG Key", 1)
        PopulateItemTypesRecord(connection, 4, "AU Key", 1)
        PopulateItemTypesRecord(connection, 5, "PT Key", 1)
        PopulateItemTypesRecord(connection, 6, "Elemental Orb", 0)
        PopulateItemTypesRecord(connection, 7, "Potion", 1)
        PopulateItemTypesRecord(connection, 8, "Goblin Ear", 1)
        PopulateItemTypesRecord(connection, 9, "Skull Fragment", 1)
        PopulateItemTypesRecord(connection, 10, "Dagger", 1)
        PopulateItemTypesRecord(connection, 11, "Earth Shard", 0)
        PopulateItemTypesRecord(connection, 12, "Water Shard", 0)
        PopulateItemTypesRecord(connection, 13, "Fire Shard", 0)
        PopulateItemTypesRecord(connection, 14, "Air Shard", 0)
        PopulateItemTypesRecord(connection, 15, "Shield", 1)
        PopulateItemTypesRecord(connection, 16, "Helmet", 1)
        PopulateItemTypesRecord(connection, 17, "Chainmail", 1)
        PopulateItemTypesRecord(connection, 18, "Shortsword", 1)
        PopulateItemTypesRecord(connection, 19, "Brodesode", 1)
        PopulateItemTypesRecord(connection, 20, "Platemail", 1)
        PopulateItemTypesRecord(connection, 21, "Rat Tail", 1)
        PopulateItemTypesRecord(connection, 22, "Holy ""Water""", 1)
        PopulateItemTypesRecord(connection, 23, "Town Portal", 1)
        PopulateItemTypesRecord(connection, 24, "Food", 1)
        PopulateItemTypesRecord(connection, 25, "Magic Egg", 1)
        PopulateItemTypesRecord(connection, 26, "Beer", 1)
        PopulateItemTypesRecord(connection, 27, "Trousers", 1)
        PopulateItemTypesRecord(connection, 28, "Pr0n Scroll", 1)
        PopulateItemTypesRecord(connection, 29, "Moon Portal", 1)
        PopulateItemTypesRecord(connection, 30, "Empty Bottle", 1)
        PopulateItemTypesRecord(connection, 31, "Book of Holy Bolt", 1)
        PopulateItemTypesRecord(connection, 32, "Membership Card", 1)
        PopulateItemTypesRecord(connection, 33, "Bong", 1)
        PopulateItemTypesRecord(connection, 34, """Herb""", 1)
        PopulateItemTypesRecord(connection, 35, "Food", 1)
        PopulateItemTypesRecord(connection, 36, "Mushroom", 1)
        PopulateItemTypesRecord(connection, 37, "Rotten Egg", 1)
        PopulateItemTypesRecord(connection, 38, "Zombie Taint", 1)
        PopulateItemTypesRecord(connection, 39, "Lotion", 1)
        PopulateItemTypesRecord(connection, 40, "Bat Wing", 1)
        PopulateItemTypesRecord(connection, 41, "Snake Fang", 1)
        PopulateItemTypesRecord(connection, 42, "Shoe Laces", 1)
        PopulateItemTypesRecord(connection, 43, "Spacesord", 1)
        PopulateItemTypesRecord(connection, 44, "Horns of Kordanor", 1)
        PopulateItemTypesRecord(connection, 45, "Amulet of HP", 1)
        PopulateItemTypesRecord(connection, 46, "Ring of HP", 1)
        PopulateItemTypesRecord(connection, 47, "Book of Purify", 1)
        PopulateItemTypesRecord(connection, 48, "Amulet of STR", 1)
        PopulateItemTypesRecord(connection, 49, "Amulet of DEX", 1)
        PopulateItemTypesRecord(connection, 50, "Amulet of POW", 1)
        PopulateItemTypesRecord(connection, 51, "Amulet of Mana", 1)
        PopulateItemTypesRecord(connection, 52, "Amulet of Yendor", 1)
    End Sub
    Sub PopulateCharacterTypeBribesRecord(connection As SqliteConnection, CharacterTypeId As Long, ItemTypeId As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterTypeBribes]([CharacterTypeId], [ItemTypeId]) VALUES (@CharacterTypeId, @ItemTypeId);", connection)
            command.Parameters.AddWithValue("@CharacterTypeId", CharacterTypeId)
            command.Parameters.AddWithValue("@ItemTypeId", ItemTypeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterTypeBribes(connection As SqliteConnection)
        PopulateCharacterTypeBribesRecord(connection, 6, 26)
        PopulateCharacterTypeBribesRecord(connection, 6, 28)
        PopulateCharacterTypeBribesRecord(connection, 7, 26)
        PopulateCharacterTypeBribesRecord(connection, 9, 28)
        PopulateCharacterTypeBribesRecord(connection, 10, 30)
        PopulateCharacterTypeBribesRecord(connection, 2, 37)
    End Sub
    Sub PopulateCharacterTypeEnemiesRecord(connection As SqliteConnection, CharacterTypeId As Long, EnemyCharacterTypeId As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterTypeEnemies]([CharacterTypeId], [EnemyCharacterTypeId]) VALUES (@CharacterTypeId, @EnemyCharacterTypeId);", connection)
            command.Parameters.AddWithValue("@CharacterTypeId", CharacterTypeId)
            command.Parameters.AddWithValue("@EnemyCharacterTypeId", EnemyCharacterTypeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterTypeEnemies(connection As SqliteConnection)
        PopulateCharacterTypeEnemiesRecord(connection, 1, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 2, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 3, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 4, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 5, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 6, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 7, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 8, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 9, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 10, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 12, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 13, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 14, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 15, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 16, 11)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 1)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 2)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 3)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 4)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 5)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 6)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 7)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 8)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 9)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 10)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 12)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 13)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 14)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 15)
        PopulateCharacterTypeEnemiesRecord(connection, 11, 16)
    End Sub
    Sub PopulateCharacterTypeLootsRecord(connection As SqliteConnection, CharacterTypeId As Long, ItemTypeId As Long?, Weight As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterTypeLoots]([CharacterTypeId], [ItemTypeId], [Weight]) VALUES (@CharacterTypeId, @ItemTypeId, @Weight);", connection)
            command.Parameters.AddWithValue("@CharacterTypeId", CharacterTypeId)
            command.Parameters.AddWithValue("@ItemTypeId", If(ItemTypeId Is Nothing, CObj(DBNull.Value), ItemTypeId))
            command.Parameters.AddWithValue("@Weight", Weight)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterTypeLoots(connection As SqliteConnection)
        PopulateCharacterTypeLootsRecord(connection, 1, Nothing, 1)
        PopulateCharacterTypeLootsRecord(connection, 1, 22, 1)
        PopulateCharacterTypeLootsRecord(connection, 2, Nothing, 2)
        PopulateCharacterTypeLootsRecord(connection, 2, 36, 1)
        PopulateCharacterTypeLootsRecord(connection, 3, Nothing, 1)
        PopulateCharacterTypeLootsRecord(connection, 3, 40, 1)
        PopulateCharacterTypeLootsRecord(connection, 4, Nothing, 1)
        PopulateCharacterTypeLootsRecord(connection, 4, 7, 1)
        PopulateCharacterTypeLootsRecord(connection, 6, Nothing, 2)
        PopulateCharacterTypeLootsRecord(connection, 6, 8, 4)
        PopulateCharacterTypeLootsRecord(connection, 6, 24, 1)
        PopulateCharacterTypeLootsRecord(connection, 6, 35, 1)
        PopulateCharacterTypeLootsRecord(connection, 7, Nothing, 2)
        PopulateCharacterTypeLootsRecord(connection, 7, 8, 5)
        PopulateCharacterTypeLootsRecord(connection, 7, 24, 2)
        PopulateCharacterTypeLootsRecord(connection, 7, 35, 1)
        PopulateCharacterTypeLootsRecord(connection, 8, 44, 1)
        PopulateCharacterTypeLootsRecord(connection, 9, Nothing, 2)
        PopulateCharacterTypeLootsRecord(connection, 9, 24, 1)
        PopulateCharacterTypeLootsRecord(connection, 9, 35, 2)
        PopulateCharacterTypeLootsRecord(connection, 10, Nothing, 1)
        PopulateCharacterTypeLootsRecord(connection, 10, 42, 1)
        PopulateCharacterTypeLootsRecord(connection, 12, Nothing, 1)
        PopulateCharacterTypeLootsRecord(connection, 12, 34, 1)
        PopulateCharacterTypeLootsRecord(connection, 13, 21, 1)
        PopulateCharacterTypeLootsRecord(connection, 14, Nothing, 1)
        PopulateCharacterTypeLootsRecord(connection, 14, 9, 3)
        PopulateCharacterTypeLootsRecord(connection, 15, Nothing, 2)
        PopulateCharacterTypeLootsRecord(connection, 15, 41, 1)
        PopulateCharacterTypeLootsRecord(connection, 16, Nothing, 1)
        PopulateCharacterTypeLootsRecord(connection, 16, 38, 3)
    End Sub
    Sub PopulateCharacterTypePartingShotsRecord(connection As SqliteConnection, CharacterTypeId As Long, PartingShot As String, Weight As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterTypePartingShots]([CharacterTypeId], [PartingShot], [Weight]) VALUES (@CharacterTypeId, @PartingShot, @Weight);", connection)
            command.Parameters.AddWithValue("@CharacterTypeId", CharacterTypeId)
            command.Parameters.AddWithValue("@PartingShot", PartingShot)
            command.Parameters.AddWithValue("@Weight", Weight)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterTypePartingShots(connection As SqliteConnection)
        PopulateCharacterTypePartingShotsRecord(connection, 6, "@#$% you!", 1)
        PopulateCharacterTypePartingShotsRecord(connection, 7, "@#$% you!", 1)
        PopulateCharacterTypePartingShotsRecord(connection, 16, "Breains!", 1)
    End Sub
    Sub PopulateDungeonLevelsRecord(connection As SqliteConnection, DungeonLevelId As Long, DungeonLevelName As String)
        Using command = New SqliteCommand("INSERT INTO [DungeonLevels]([DungeonLevelId], [DungeonLevelName]) VALUES (@DungeonLevelId, @DungeonLevelName);", connection)
            command.Parameters.AddWithValue("@DungeonLevelId", DungeonLevelId)
            command.Parameters.AddWithValue("@DungeonLevelName", DungeonLevelName)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateDungeonLevels(connection As SqliteConnection)
        PopulateDungeonLevelsRecord(connection, 1, "Level I")
        PopulateDungeonLevelsRecord(connection, 2, "Level II")
        PopulateDungeonLevelsRecord(connection, 3, "Level III")
        PopulateDungeonLevelsRecord(connection, 4, "Level IV")
        PopulateDungeonLevelsRecord(connection, 5, "Level V")
        PopulateDungeonLevelsRecord(connection, 6, "The Moon")
    End Sub
    Sub PopulateCharacterTypeSpawnCountsRecord(connection As SqliteConnection, CharacterTypeId As Long, DungeonLevelId As Long, SpawnCount As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterTypeSpawnCounts]([CharacterTypeId], [DungeonLevelId], [SpawnCount]) VALUES (@CharacterTypeId, @DungeonLevelId, @SpawnCount);", connection)
            command.Parameters.AddWithValue("@CharacterTypeId", CharacterTypeId)
            command.Parameters.AddWithValue("@DungeonLevelId", DungeonLevelId)
            command.Parameters.AddWithValue("@SpawnCount", SpawnCount)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterTypeSpawnCounts(connection As SqliteConnection)
        PopulateCharacterTypeSpawnCountsRecord(connection, 1, 1, 1)
        PopulateCharacterTypeSpawnCountsRecord(connection, 1, 2, 10)
        PopulateCharacterTypeSpawnCountsRecord(connection, 1, 3, 25)
        PopulateCharacterTypeSpawnCountsRecord(connection, 2, 1, 24)
        PopulateCharacterTypeSpawnCountsRecord(connection, 2, 2, 12)
        PopulateCharacterTypeSpawnCountsRecord(connection, 3, 1, 15)
        PopulateCharacterTypeSpawnCountsRecord(connection, 3, 2, 30)
        PopulateCharacterTypeSpawnCountsRecord(connection, 3, 3, 45)
        PopulateCharacterTypeSpawnCountsRecord(connection, 3, 4, 30)
        PopulateCharacterTypeSpawnCountsRecord(connection, 3, 5, 15)
        PopulateCharacterTypeSpawnCountsRecord(connection, 4, 3, 1)
        PopulateCharacterTypeSpawnCountsRecord(connection, 4, 4, 10)
        PopulateCharacterTypeSpawnCountsRecord(connection, 4, 5, 25)
        PopulateCharacterTypeSpawnCountsRecord(connection, 5, 4, 1)
        PopulateCharacterTypeSpawnCountsRecord(connection, 6, 1, 30)
        PopulateCharacterTypeSpawnCountsRecord(connection, 6, 2, 45)
        PopulateCharacterTypeSpawnCountsRecord(connection, 6, 3, 30)
        PopulateCharacterTypeSpawnCountsRecord(connection, 6, 4, 15)
        PopulateCharacterTypeSpawnCountsRecord(connection, 7, 1, 5)
        PopulateCharacterTypeSpawnCountsRecord(connection, 7, 2, 15)
        PopulateCharacterTypeSpawnCountsRecord(connection, 7, 3, 30)
        PopulateCharacterTypeSpawnCountsRecord(connection, 7, 4, 45)
        PopulateCharacterTypeSpawnCountsRecord(connection, 7, 5, 30)
        PopulateCharacterTypeSpawnCountsRecord(connection, 8, 5, 1)
        PopulateCharacterTypeSpawnCountsRecord(connection, 9, 1, 30)
        PopulateCharacterTypeSpawnCountsRecord(connection, 9, 2, 15)
        PopulateCharacterTypeSpawnCountsRecord(connection, 10, 6, 100)
        PopulateCharacterTypeSpawnCountsRecord(connection, 12, 2, 1)
        PopulateCharacterTypeSpawnCountsRecord(connection, 12, 3, 15)
        PopulateCharacterTypeSpawnCountsRecord(connection, 12, 4, 30)
        PopulateCharacterTypeSpawnCountsRecord(connection, 12, 5, 45)
        PopulateCharacterTypeSpawnCountsRecord(connection, 14, 1, 30)
        PopulateCharacterTypeSpawnCountsRecord(connection, 14, 2, 45)
        PopulateCharacterTypeSpawnCountsRecord(connection, 14, 3, 30)
        PopulateCharacterTypeSpawnCountsRecord(connection, 14, 4, 15)
        PopulateCharacterTypeSpawnCountsRecord(connection, 15, 1, 15)
        PopulateCharacterTypeSpawnCountsRecord(connection, 15, 2, 30)
        PopulateCharacterTypeSpawnCountsRecord(connection, 15, 3, 45)
        PopulateCharacterTypeSpawnCountsRecord(connection, 15, 4, 30)
        PopulateCharacterTypeSpawnCountsRecord(connection, 15, 5, 15)
        PopulateCharacterTypeSpawnCountsRecord(connection, 16, 2, 30)
        PopulateCharacterTypeSpawnCountsRecord(connection, 16, 3, 45)
        PopulateCharacterTypeSpawnCountsRecord(connection, 16, 4, 30)
    End Sub
    Sub PopulateLocationTypesRecord(connection As SqliteConnection, LocationTypeId As Long, LocationTypeName As String, IsDungeon As Long, CanMap As Long, RequiresMP As Long)
        Using command = New SqliteCommand("INSERT INTO [LocationTypes]([LocationTypeId], [LocationTypeName], [IsDungeon], [CanMap], [RequiresMP]) VALUES (@LocationTypeId, @LocationTypeName, @IsDungeon, @CanMap, @RequiresMP);", connection)
            command.Parameters.AddWithValue("@LocationTypeId", LocationTypeId)
            command.Parameters.AddWithValue("@LocationTypeName", LocationTypeName)
            command.Parameters.AddWithValue("@IsDungeon", IsDungeon)
            command.Parameters.AddWithValue("@CanMap", CanMap)
            command.Parameters.AddWithValue("@RequiresMP", RequiresMP)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateLocationTypes(connection As SqliteConnection)
        PopulateLocationTypesRecord(connection, 1, "Town Square", 0, 0, 0)
        PopulateLocationTypesRecord(connection, 2, "Town", 0, 0, 0)
        PopulateLocationTypesRecord(connection, 3, "Church Entrance", 0, 0, 0)
        PopulateLocationTypesRecord(connection, 4, "Dungeon", 1, 1, 1)
        PopulateLocationTypesRecord(connection, 5, "Dungeon Dead End", 1, 1, 1)
        PopulateLocationTypesRecord(connection, 6, "Dungeon Boss", 1, 1, 1)
        PopulateLocationTypesRecord(connection, 7, "Cellar", 1, 0, 1)
        PopulateLocationTypesRecord(connection, 8, "Moon", 1, 1, 1)
    End Sub
    Sub PopulateCharacterTypeSpawnLocationsRecord(connection As SqliteConnection, CharacterTypeId As Long, DungeonLevelId As Long, LocationTypeId As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterTypeSpawnLocations]([CharacterTypeId], [DungeonLevelId], [LocationTypeId]) VALUES (@CharacterTypeId, @DungeonLevelId, @LocationTypeId);", connection)
            command.Parameters.AddWithValue("@CharacterTypeId", CharacterTypeId)
            command.Parameters.AddWithValue("@DungeonLevelId", DungeonLevelId)
            command.Parameters.AddWithValue("@LocationTypeId", LocationTypeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterTypeSpawnLocations(connection As SqliteConnection)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 1, 1, 6)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 1, 2, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 1, 2, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 1, 3, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 1, 3, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 1, 4, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 1, 4, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 1, 5, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 1, 5, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 2, 1, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 2, 2, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 2, 2, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 2, 3, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 2, 3, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 2, 4, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 2, 4, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 2, 5, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 2, 5, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 3, 1, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 3, 2, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 3, 3, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 3, 4, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 3, 5, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 4, 3, 6)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 4, 4, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 4, 4, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 4, 5, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 4, 5, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 5, 4, 6)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 6, 1, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 6, 2, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 6, 3, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 6, 4, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 6, 5, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 7, 1, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 7, 2, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 7, 2, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 7, 3, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 7, 3, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 7, 4, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 7, 4, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 7, 5, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 7, 5, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 8, 5, 6)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 9, 1, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 9, 2, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 9, 2, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 9, 3, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 9, 3, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 9, 4, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 9, 4, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 9, 5, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 9, 5, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 10, 6, 8)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 12, 2, 6)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 12, 3, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 12, 3, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 12, 4, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 12, 4, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 12, 5, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 12, 5, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 14, 1, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 14, 2, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 14, 3, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 14, 4, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 14, 5, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 15, 1, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 15, 2, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 15, 3, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 15, 4, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 15, 5, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 16, 1, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 16, 2, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 16, 2, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 16, 3, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 16, 3, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 16, 4, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 16, 4, 5)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 16, 5, 4)
        PopulateCharacterTypeSpawnLocationsRecord(connection, 16, 5, 5)
    End Sub
    Sub PopulateEquipSlotsRecord(connection As SqliteConnection, EquipSlotId As Long, EquipSlotName As String)
        Using command = New SqliteCommand("INSERT INTO [EquipSlots]([EquipSlotId], [EquipSlotName]) VALUES (@EquipSlotId, @EquipSlotName);", connection)
            command.Parameters.AddWithValue("@EquipSlotId", EquipSlotId)
            command.Parameters.AddWithValue("@EquipSlotName", EquipSlotName)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateEquipSlots(connection As SqliteConnection)
        PopulateEquipSlotsRecord(connection, 1, "Weapon")
        PopulateEquipSlotsRecord(connection, 2, "Shield")
        PopulateEquipSlotsRecord(connection, 3, "Head")
        PopulateEquipSlotsRecord(connection, 4, "Torso")
        PopulateEquipSlotsRecord(connection, 5, "Legs")
        PopulateEquipSlotsRecord(connection, 6, "Neck")
        PopulateEquipSlotsRecord(connection, 7, "LHand")
        PopulateEquipSlotsRecord(connection, 8, "RHand")
    End Sub
    Sub PopulateQuestTypesRecord(connection As SqliteConnection, QuestTypeId As Long, CanAcceptEventName As String, AcceptEventName As String, CanCompleteEventName As String, CompleteEventName As String)
        Using command = New SqliteCommand("INSERT INTO [QuestTypes]([QuestTypeId], [CanAcceptEventName], [AcceptEventName], [CanCompleteEventName], [CompleteEventName]) VALUES (@QuestTypeId, @CanAcceptEventName, @AcceptEventName, @CanCompleteEventName, @CompleteEventName);", connection)
            command.Parameters.AddWithValue("@QuestTypeId", QuestTypeId)
            command.Parameters.AddWithValue("@CanAcceptEventName", CanAcceptEventName)
            command.Parameters.AddWithValue("@AcceptEventName", AcceptEventName)
            command.Parameters.AddWithValue("@CanCompleteEventName", CanCompleteEventName)
            command.Parameters.AddWithValue("@CompleteEventName", CompleteEventName)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateQuestTypes(connection As SqliteConnection)
        PopulateQuestTypesRecord(connection, 1, "CharacterCanAcceptCellarRatsQuest", "CharacterAcceptCellarRatsQuest", "CharacterCanCompleteCellarRatsQuest", "CharacterCompleteCellarRatsQuest")
    End Sub
    Sub PopulateItemStatisticTypesRecord(connection As SqliteConnection, ItemStatisticTypeId As Long, DefaultValue As Long)
        Using command = New SqliteCommand("INSERT INTO [ItemStatisticTypes]([ItemStatisticTypeId], [DefaultValue]) VALUES (@ItemStatisticTypeId, @DefaultValue);", connection)
            command.Parameters.AddWithValue("@ItemStatisticTypeId", ItemStatisticTypeId)
            command.Parameters.AddWithValue("@DefaultValue", DefaultValue)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemStatisticTypes(connection As SqliteConnection)
        PopulateItemStatisticTypesRecord(connection, 1, 0)
    End Sub
    Sub PopulateItemTypeEquipSlotsRecord(connection As SqliteConnection, ItemTypeId As Long, EquipSlotId As Long)
        Using command = New SqliteCommand("INSERT INTO [ItemTypeEquipSlots]([ItemTypeId], [EquipSlotId]) VALUES (@ItemTypeId, @EquipSlotId);", connection)
            command.Parameters.AddWithValue("@ItemTypeId", ItemTypeId)
            command.Parameters.AddWithValue("@EquipSlotId", EquipSlotId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypeEquipSlots(connection As SqliteConnection)
        PopulateItemTypeEquipSlotsRecord(connection, 10, 1)
        PopulateItemTypeEquipSlotsRecord(connection, 15, 2)
        PopulateItemTypeEquipSlotsRecord(connection, 16, 3)
        PopulateItemTypeEquipSlotsRecord(connection, 17, 4)
        PopulateItemTypeEquipSlotsRecord(connection, 18, 1)
        PopulateItemTypeEquipSlotsRecord(connection, 19, 1)
        PopulateItemTypeEquipSlotsRecord(connection, 20, 4)
        PopulateItemTypeEquipSlotsRecord(connection, 27, 5)
        PopulateItemTypeEquipSlotsRecord(connection, 30, 1)
        PopulateItemTypeEquipSlotsRecord(connection, 43, 1)
        PopulateItemTypeEquipSlotsRecord(connection, 45, 6)
        PopulateItemTypeEquipSlotsRecord(connection, 46, 7)
        PopulateItemTypeEquipSlotsRecord(connection, 46, 8)
        PopulateItemTypeEquipSlotsRecord(connection, 48, 6)
        PopulateItemTypeEquipSlotsRecord(connection, 49, 6)
        PopulateItemTypeEquipSlotsRecord(connection, 50, 6)
        PopulateItemTypeEquipSlotsRecord(connection, 51, 6)
        PopulateItemTypeEquipSlotsRecord(connection, 52, 6)
    End Sub
    Sub PopulateItemTypeEventsRecord(connection As SqliteConnection, ItemTypeId As Long, EventId As Long, EventName As String)
        Using command = New SqliteCommand("INSERT INTO [ItemTypeEvents]([ItemTypeId], [EventId], [EventName]) VALUES (@ItemTypeId, @EventId, @EventName);", connection)
            command.Parameters.AddWithValue("@ItemTypeId", ItemTypeId)
            command.Parameters.AddWithValue("@EventId", EventId)
            command.Parameters.AddWithValue("@EventName", EventName)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypeEvents(connection As SqliteConnection)
        PopulateItemTypeEventsRecord(connection, 7, 2, "AlwaysTrue")
        PopulateItemTypeEventsRecord(connection, 7, 3, "DrinkPotion")
        PopulateItemTypeEventsRecord(connection, 11, 2, "CanUseEarthShard")
        PopulateItemTypeEventsRecord(connection, 11, 3, "UseEarthShard")
        PopulateItemTypeEventsRecord(connection, 12, 2, "CanUseWaterShard")
        PopulateItemTypeEventsRecord(connection, 12, 3, "UseWaterShard")
        PopulateItemTypeEventsRecord(connection, 13, 2, "CanUseFireShard")
        PopulateItemTypeEventsRecord(connection, 13, 3, "UseFireShard")
        PopulateItemTypeEventsRecord(connection, 14, 2, "CanUseAirShard")
        PopulateItemTypeEventsRecord(connection, 14, 3, "UseAirShard")
        PopulateItemTypeEventsRecord(connection, 22, 2, "IsFightingUndead")
        PopulateItemTypeEventsRecord(connection, 22, 3, "UseHolyWater")
        PopulateItemTypeEventsRecord(connection, 23, 2, "IsInDungeon")
        PopulateItemTypeEventsRecord(connection, 23, 3, "UseTownPortal")
        PopulateItemTypeEventsRecord(connection, 24, 2, "AlwaysTrue")
        PopulateItemTypeEventsRecord(connection, 24, 3, "EatFood")
        PopulateItemTypeEventsRecord(connection, 25, 2, "AlwaysTrue")
        PopulateItemTypeEventsRecord(connection, 25, 3, "UseMagicEgg")
        PopulateItemTypeEventsRecord(connection, 26, 2, "CanUseBeer")
        PopulateItemTypeEventsRecord(connection, 26, 3, "UseBeer")
        PopulateItemTypeEventsRecord(connection, 28, 2, "CanUsePr0n")
        PopulateItemTypeEventsRecord(connection, 28, 3, "UsePr0n")
        PopulateItemTypeEventsRecord(connection, 29, 2, "IsInDungeon")
        PopulateItemTypeEventsRecord(connection, 29, 3, "UseMoonPortal")
        PopulateItemTypeEventsRecord(connection, 30, 2, "CanUseBottle")
        PopulateItemTypeEventsRecord(connection, 30, 3, "UseBottle")
        PopulateItemTypeEventsRecord(connection, 31, 2, "CanLearnHolyBolt")
        PopulateItemTypeEventsRecord(connection, 31, 3, "LearnHolyBolt")
        PopulateItemTypeEventsRecord(connection, 34, 2, "HasBong")
        PopulateItemTypeEventsRecord(connection, 34, 3, "UseHerb")
        PopulateItemTypeEventsRecord(connection, 35, 1, "PurifyFood")
        PopulateItemTypeEventsRecord(connection, 35, 2, "AlwaysTrue")
        PopulateItemTypeEventsRecord(connection, 35, 3, "UseRottenFood")
        PopulateItemTypeEventsRecord(connection, 37, 2, "CanUseRottenEgg")
        PopulateItemTypeEventsRecord(connection, 37, 3, "UseRottenEgg")
        PopulateItemTypeEventsRecord(connection, 47, 2, "CanLearnPurify")
        PopulateItemTypeEventsRecord(connection, 47, 3, "LearnPurify")
    End Sub
    Sub PopulateShoppeTypesRecord(connection As SqliteConnection, ShoppeTypeId As Long, ShoppeTypeName As String)
        Using command = New SqliteCommand("INSERT INTO [ShoppeTypes]([ShoppeTypeId], [ShoppeTypeName]) VALUES (@ShoppeTypeId, @ShoppeTypeName);", connection)
            command.Parameters.AddWithValue("@ShoppeTypeId", ShoppeTypeId)
            command.Parameters.AddWithValue("@ShoppeTypeName", ShoppeTypeName)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateShoppeTypes(connection As SqliteConnection)
        PopulateShoppeTypesRecord(connection, 1, "Magic")
        PopulateShoppeTypesRecord(connection, 2, "Blacksmith")
        PopulateShoppeTypesRecord(connection, 3, "Innkeeper")
        PopulateShoppeTypesRecord(connection, 4, "Healer")
        PopulateShoppeTypesRecord(connection, 5, "Black Market")
    End Sub
    Sub PopulateItemTypeShopTypesRecord(connection As SqliteConnection, ItemTypeId As Long, ShoppeTypeId As Long, TransactionTypeId As Long)
        Using command = New SqliteCommand("INSERT INTO [ItemTypeShopTypes]([ItemTypeId], [ShoppeTypeId], [TransactionTypeId]) VALUES (@ItemTypeId, @ShoppeTypeId, @TransactionTypeId);", connection)
            command.Parameters.AddWithValue("@ItemTypeId", ItemTypeId)
            command.Parameters.AddWithValue("@ShoppeTypeId", ShoppeTypeId)
            command.Parameters.AddWithValue("@TransactionTypeId", TransactionTypeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypeShopTypes(connection As SqliteConnection)
        PopulateItemTypeShopTypesRecord(connection, 7, 4, 2)
        PopulateItemTypeShopTypesRecord(connection, 8, 1, 2)
        PopulateItemTypeShopTypesRecord(connection, 9, 1, 1)
        PopulateItemTypeShopTypesRecord(connection, 10, 2, 1)
        PopulateItemTypeShopTypesRecord(connection, 10, 2, 2)
        PopulateItemTypeShopTypesRecord(connection, 10, 2, 3)
        PopulateItemTypeShopTypesRecord(connection, 15, 2, 1)
        PopulateItemTypeShopTypesRecord(connection, 15, 2, 2)
        PopulateItemTypeShopTypesRecord(connection, 15, 2, 3)
        PopulateItemTypeShopTypesRecord(connection, 16, 2, 1)
        PopulateItemTypeShopTypesRecord(connection, 16, 2, 2)
        PopulateItemTypeShopTypesRecord(connection, 16, 2, 3)
        PopulateItemTypeShopTypesRecord(connection, 17, 2, 1)
        PopulateItemTypeShopTypesRecord(connection, 17, 2, 2)
        PopulateItemTypeShopTypesRecord(connection, 17, 2, 3)
        PopulateItemTypeShopTypesRecord(connection, 18, 2, 1)
        PopulateItemTypeShopTypesRecord(connection, 18, 2, 2)
        PopulateItemTypeShopTypesRecord(connection, 18, 2, 3)
        PopulateItemTypeShopTypesRecord(connection, 19, 2, 1)
        PopulateItemTypeShopTypesRecord(connection, 19, 2, 2)
        PopulateItemTypeShopTypesRecord(connection, 29, 2, 3)
        PopulateItemTypeShopTypesRecord(connection, 20, 2, 1)
        PopulateItemTypeShopTypesRecord(connection, 20, 2, 2)
        PopulateItemTypeShopTypesRecord(connection, 20, 2, 3)
        PopulateItemTypeShopTypesRecord(connection, 21, 1, 2)
        PopulateItemTypeShopTypesRecord(connection, 22, 4, 2)
        PopulateItemTypeShopTypesRecord(connection, 23, 1, 2)
        PopulateItemTypeShopTypesRecord(connection, 24, 3, 2)
        PopulateItemTypeShopTypesRecord(connection, 25, 1, 2)
        PopulateItemTypeShopTypesRecord(connection, 26, 3, 2)
        PopulateItemTypeShopTypesRecord(connection, 27, 5, 2)
        PopulateItemTypeShopTypesRecord(connection, 28, 5, 2)
        PopulateItemTypeShopTypesRecord(connection, 29, 1, 2)
        PopulateItemTypeShopTypesRecord(connection, 31, 1, 2)
        PopulateItemTypeShopTypesRecord(connection, 33, 1, 2)
        PopulateItemTypeShopTypesRecord(connection, 34, 1, 2)
        PopulateItemTypeShopTypesRecord(connection, 36, 1, 2)
        PopulateItemTypeShopTypesRecord(connection, 38, 1, 2)
        PopulateItemTypeShopTypesRecord(connection, 39, 5, 2)
        PopulateItemTypeShopTypesRecord(connection, 40, 1, 2)
        PopulateItemTypeShopTypesRecord(connection, 41, 1, 2)
        PopulateItemTypeShopTypesRecord(connection, 47, 1, 2)
        PopulateItemTypeShopTypesRecord(connection, 52, 5, 2)
    End Sub
    Sub PopulateItemTypeSpawnCountsRecord(connection As SqliteConnection, ItemTypeId As Long, DungeonLevelId As Long, SpawnDice As String)
        Using command = New SqliteCommand("INSERT INTO [ItemTypeSpawnCounts]([ItemTypeId], [DungeonLevelId], [SpawnDice]) VALUES (@ItemTypeId, @DungeonLevelId, @SpawnDice);", connection)
            command.Parameters.AddWithValue("@ItemTypeId", ItemTypeId)
            command.Parameters.AddWithValue("@DungeonLevelId", DungeonLevelId)
            command.Parameters.AddWithValue("@SpawnDice", SpawnDice)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypeSpawnCounts(connection As SqliteConnection)
        PopulateItemTypeSpawnCountsRecord(connection, 7, 1, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, 7, 2, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, 7, 3, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, 7, 4, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, 7, 5, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, 10, 1, "4d6")
        PopulateItemTypeSpawnCountsRecord(connection, 10, 2, "2d6")
        PopulateItemTypeSpawnCountsRecord(connection, 11, 2, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, 12, 4, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, 13, 3, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, 14, 1, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, 15, 1, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, 16, 1, "3d6")
        PopulateItemTypeSpawnCountsRecord(connection, 17, 1, "1d6")
        PopulateItemTypeSpawnCountsRecord(connection, 18, 1, "2d6")
        PopulateItemTypeSpawnCountsRecord(connection, 18, 2, "1d6")
        PopulateItemTypeSpawnCountsRecord(connection, 19, 2, "2d6")
        PopulateItemTypeSpawnCountsRecord(connection, 19, 3, "1d6")
        PopulateItemTypeSpawnCountsRecord(connection, 20, 2, "1d6")
        PopulateItemTypeSpawnCountsRecord(connection, 43, 6, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, 45, 1, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, 48, 4, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, 50, 3, "1d1")
        PopulateItemTypeSpawnCountsRecord(connection, 51, 5, "1d1")
    End Sub
    Sub PopulateItemTypeSpawnLocationTypesRecord(connection As SqliteConnection, ItemTypeId As Long, DungeonLevelId As Long, LocationTypeId As Long)
        Using command = New SqliteCommand("INSERT INTO [ItemTypeSpawnLocationTypes]([ItemTypeId], [DungeonLevelId], [LocationTypeId]) VALUES (@ItemTypeId, @DungeonLevelId, @LocationTypeId);", connection)
            command.Parameters.AddWithValue("@ItemTypeId", ItemTypeId)
            command.Parameters.AddWithValue("@DungeonLevelId", DungeonLevelId)
            command.Parameters.AddWithValue("@LocationTypeId", LocationTypeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypeSpawnLocationTypes(connection As SqliteConnection)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 1, 1, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 1, 2, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 1, 3, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 1, 4, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 1, 5, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 2, 1, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 3, 2, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 4, 3, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 5, 4, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 7, 1, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 7, 1, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 7, 2, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 7, 2, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 7, 3, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 7, 3, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 7, 4, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 7, 4, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 7, 5, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 7, 5, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 10, 1, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 10, 2, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 10, 3, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 10, 4, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 10, 5, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 11, 2, 6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 12, 4, 6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 14, 1, 6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 15, 1, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 15, 1, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 15, 2, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 15, 2, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 15, 3, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 15, 3, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 15, 4, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 15, 4, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 15, 5, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 15, 5, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 16, 1, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 16, 1, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 16, 2, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 16, 2, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 16, 3, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 16, 3, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 16, 4, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 16, 4, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 16, 5, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 16, 5, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 17, 1, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 17, 2, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 17, 2, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 17, 3, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 17, 3, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 17, 4, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 17, 4, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 17, 5, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 17, 5, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 18, 1, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 18, 2, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 18, 3, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 18, 4, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 18, 5, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 19, 1, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 19, 2, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 19, 3, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 19, 4, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 19, 5, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 20, 2, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 20, 3, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 20, 3, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 20, 4, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 20, 4, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 20, 5, 4)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 20, 5, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 43, 6, 8)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 45, 1, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 45, 1, 6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 48, 4, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 48, 4, 6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 50, 3, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 50, 3, 6)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 51, 2, 5)
        PopulateItemTypeSpawnLocationTypesRecord(connection, 51, 2, 6)
    End Sub
    Sub PopulateItemTypeCharacterStatisticBuffsRecord(connection As SqliteConnection, ItemTypeId As Long, CharacterStatisticTypeId As Long, Buff As Long)
        Using command = New SqliteCommand("INSERT INTO [ItemTypeCharacterStatisticBuffs]([ItemTypeId], [CharacterStatisticTypeId], [Buff]) VALUES (@ItemTypeId, @CharacterStatisticTypeId, @Buff);", connection)
            command.Parameters.AddWithValue("@ItemTypeId", ItemTypeId)
            command.Parameters.AddWithValue("@CharacterStatisticTypeId", CharacterStatisticTypeId)
            command.Parameters.AddWithValue("@Buff", Buff)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypeCharacterStatisticBuffs(connection As SqliteConnection)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, 45, 6, 1)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, 46, 6, 1)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, 49, 2, 1)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, 50, 5, 1)
        PopulateItemTypeCharacterStatisticBuffsRecord(connection, 51, 8, 1)
    End Sub
    Sub PopulateItemTypeStatisticTypesRecord(connection As SqliteConnection, ItemTypeStatisticTypeId As Long, ItemTypeStatisticTypeName As String)
        Using command = New SqliteCommand("INSERT INTO [ItemTypeStatisticTypes]([ItemTypeStatisticTypeId], [ItemTypeStatisticTypeName]) VALUES (@ItemTypeStatisticTypeId, @ItemTypeStatisticTypeName);", connection)
            command.Parameters.AddWithValue("@ItemTypeStatisticTypeId", ItemTypeStatisticTypeId)
            command.Parameters.AddWithValue("@ItemTypeStatisticTypeName", ItemTypeStatisticTypeName)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypeStatisticTypes(connection As SqliteConnection)
        PopulateItemTypeStatisticTypesRecord(connection, 1, "Encumbrance")
        PopulateItemTypeStatisticTypesRecord(connection, 2, "AttackDice")
        PopulateItemTypeStatisticTypesRecord(connection, 3, "MaximumDamage")
        PopulateItemTypeStatisticTypesRecord(connection, 4, "DefendDice")
        PopulateItemTypeStatisticTypesRecord(connection, 5, "MaximumDurability")
        PopulateItemTypeStatisticTypesRecord(connection, 6, "Offer")
        PopulateItemTypeStatisticTypesRecord(connection, 7, "Price")
        PopulateItemTypeStatisticTypesRecord(connection, 8, "RepairPrice")
    End Sub
    Sub PopulateItemTypeStatisticsRecord(connection As SqliteConnection, ItemTypeId As Long, ItemTypeStatisticTypeId As Long, ItemTypeStatisticValue As Long)
        Using command = New SqliteCommand("INSERT INTO [ItemTypeStatistics]([ItemTypeId], [ItemTypeStatisticTypeId], [ItemTypeStatisticValue]) VALUES (@ItemTypeId, @ItemTypeStatisticTypeId, @ItemTypeStatisticValue);", connection)
            command.Parameters.AddWithValue("@ItemTypeId", ItemTypeId)
            command.Parameters.AddWithValue("@ItemTypeStatisticTypeId", ItemTypeStatisticTypeId)
            command.Parameters.AddWithValue("@ItemTypeStatisticValue", ItemTypeStatisticValue)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemTypeStatistics(connection As SqliteConnection)
        PopulateItemTypeStatisticsRecord(connection, 7, 1, 2)
        PopulateItemTypeStatisticsRecord(connection, 7, 7, 15)
        PopulateItemTypeStatisticsRecord(connection, 8, 6, 5)
        PopulateItemTypeStatisticsRecord(connection, 9, 6, 5)
        PopulateItemTypeStatisticsRecord(connection, 10, 1, 1)
        PopulateItemTypeStatisticsRecord(connection, 10, 2, 2)
        PopulateItemTypeStatisticsRecord(connection, 10, 3, 1)
        PopulateItemTypeStatisticsRecord(connection, 10, 5, 10)
        PopulateItemTypeStatisticsRecord(connection, 10, 6, 1)
        PopulateItemTypeStatisticsRecord(connection, 10, 7, 5)
        PopulateItemTypeStatisticsRecord(connection, 10, 8, 2)
        PopulateItemTypeStatisticsRecord(connection, 15, 1, 5)
        PopulateItemTypeStatisticsRecord(connection, 15, 4, 2)
        PopulateItemTypeStatisticsRecord(connection, 15, 5, 10)
        PopulateItemTypeStatisticsRecord(connection, 15, 6, 3)
        PopulateItemTypeStatisticsRecord(connection, 15, 7, 15)
        PopulateItemTypeStatisticsRecord(connection, 15, 8, 6)
        PopulateItemTypeStatisticsRecord(connection, 16, 1, 2)
        PopulateItemTypeStatisticsRecord(connection, 16, 4, 2)
        PopulateItemTypeStatisticsRecord(connection, 16, 5, 10)
        PopulateItemTypeStatisticsRecord(connection, 16, 6, 2)
        PopulateItemTypeStatisticsRecord(connection, 16, 7, 10)
        PopulateItemTypeStatisticsRecord(connection, 16, 8, 4)
        PopulateItemTypeStatisticsRecord(connection, 17, 1, 20)
        PopulateItemTypeStatisticsRecord(connection, 17, 3, 2)
        PopulateItemTypeStatisticsRecord(connection, 17, 4, 2)
        PopulateItemTypeStatisticsRecord(connection, 17, 6, 10)
        PopulateItemTypeStatisticsRecord(connection, 17, 7, 50)
        PopulateItemTypeStatisticsRecord(connection, 17, 8, 20)
        PopulateItemTypeStatisticsRecord(connection, 18, 1, 5)
        PopulateItemTypeStatisticsRecord(connection, 18, 3, 2)
        PopulateItemTypeStatisticsRecord(connection, 18, 2, 4)
        PopulateItemTypeStatisticsRecord(connection, 18, 5, 20)
        PopulateItemTypeStatisticsRecord(connection, 18, 6, 5)
        PopulateItemTypeStatisticsRecord(connection, 18, 7, 25)
        PopulateItemTypeStatisticsRecord(connection, 18, 8, 10)
        PopulateItemTypeStatisticsRecord(connection, 19, 1, 10)
        PopulateItemTypeStatisticsRecord(connection, 19, 2, 6)
        PopulateItemTypeStatisticsRecord(connection, 19, 3, 3)
        PopulateItemTypeStatisticsRecord(connection, 19, 5, 40)
        PopulateItemTypeStatisticsRecord(connection, 19, 6, 20)
        PopulateItemTypeStatisticsRecord(connection, 19, 7, 100)
        PopulateItemTypeStatisticsRecord(connection, 19, 8, 40)
        PopulateItemTypeStatisticsRecord(connection, 20, 1, 40)
        PopulateItemTypeStatisticsRecord(connection, 20, 4, 4)
        PopulateItemTypeStatisticsRecord(connection, 20, 5, 50)
        PopulateItemTypeStatisticsRecord(connection, 20, 6, 50)
        PopulateItemTypeStatisticsRecord(connection, 20, 7, 250)
        PopulateItemTypeStatisticsRecord(connection, 20, 8, 100)
        PopulateItemTypeStatisticsRecord(connection, 21, 6, 1)
        PopulateItemTypeStatisticsRecord(connection, 22, 7, 10)
        PopulateItemTypeStatisticsRecord(connection, 23, 7, 50)
        PopulateItemTypeStatisticsRecord(connection, 24, 7, 2)
        PopulateItemTypeStatisticsRecord(connection, 25, 6, 100)
        PopulateItemTypeStatisticsRecord(connection, 26, 1, 2)
        PopulateItemTypeStatisticsRecord(connection, 26, 7, 5)
        PopulateItemTypeStatisticsRecord(connection, 27, 7, 100)
        PopulateItemTypeStatisticsRecord(connection, 28, 7, 10)
        PopulateItemTypeStatisticsRecord(connection, 29, 7, 5000)
        PopulateItemTypeStatisticsRecord(connection, 30, 1, 1)
        PopulateItemTypeStatisticsRecord(connection, 30, 2, 2)
        PopulateItemTypeStatisticsRecord(connection, 30, 3, 1)
        PopulateItemTypeStatisticsRecord(connection, 30, 5, 3)
        PopulateItemTypeStatisticsRecord(connection, 31, 7, 100)
        PopulateItemTypeStatisticsRecord(connection, 32, 6, 10)
        PopulateItemTypeStatisticsRecord(connection, 33, 7, 25)
        PopulateItemTypeStatisticsRecord(connection, 34, 7, 5)
        PopulateItemTypeStatisticsRecord(connection, 36, 6, 25)
        PopulateItemTypeStatisticsRecord(connection, 38, 6, 5)
        PopulateItemTypeStatisticsRecord(connection, 39, 1, 2)
        PopulateItemTypeStatisticsRecord(connection, 39, 6, 5)
        PopulateItemTypeStatisticsRecord(connection, 39, 7, 25)
        PopulateItemTypeStatisticsRecord(connection, 40, 6, 3)
        PopulateItemTypeStatisticsRecord(connection, 41, 6, 3)
        PopulateItemTypeStatisticsRecord(connection, 43, 1, 5)
        PopulateItemTypeStatisticsRecord(connection, 43, 3, 10)
        PopulateItemTypeStatisticsRecord(connection, 43, 4, 5)
        PopulateItemTypeStatisticsRecord(connection, 43, 6, 100)
        PopulateItemTypeStatisticsRecord(connection, 47, 7, 50)
        PopulateItemTypeStatisticsRecord(connection, 52, 7, 1000)
    End Sub
    Sub PopulateFeatureTypesRecord(connection As SqliteConnection, FeatureTypeId As Long, FeatureTypeName As String, LocationTypeId As Long, InteractionMode As Long)
        Using command = New SqliteCommand("INSERT INTO [FeatureTypes]([FeatureTypeId], [FeatureTypeName], [LocationTypeId], [InteractionMode]) VALUES (@FeatureTypeId, @FeatureTypeName, @LocationTypeId, @InteractionMode);", connection)
            command.Parameters.AddWithValue("@FeatureTypeId", FeatureTypeId)
            command.Parameters.AddWithValue("@FeatureTypeName", FeatureTypeName)
            command.Parameters.AddWithValue("@LocationTypeId", LocationTypeId)
            command.Parameters.AddWithValue("@InteractionMode", InteractionMode)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateFeatureTypes(connection As SqliteConnection)
        PopulateFeatureTypesRecord(connection, 1, "Zooperdan the Elder", 1, 4)
        PopulateFeatureTypesRecord(connection, 2, "Graham the Innkeeper", 2, 5)
        PopulateFeatureTypesRecord(connection, 3, "Yermom the Drunk", 2, 6)
        PopulateFeatureTypesRecord(connection, 4, "Sander the Chicken", 2, 7)
        PopulateFeatureTypesRecord(connection, 5, """Honest"" Dan", 2, 8)
        PopulateFeatureTypesRecord(connection, 6, "Marcus the Black Mage", 2, 9)
        PopulateFeatureTypesRecord(connection, 7, "Samuli the Blacksmith", 2, 10)
        PopulateFeatureTypesRecord(connection, 8, "Nihilist Healer Marten", 2, 12)
        PopulateFeatureTypesRecord(connection, 9, "David the Constable", 2, 11)
    End Sub
    Sub PopulateDirectionsRecord(connection As SqliteConnection, DirectionId As Long, DirectionName As String, Abbreviation As String, IsCardinal As Long, PreviousDirectionId As Long?, OppositeDirectionId As Long, NextDirectionId As Long?)
        Using command = New SqliteCommand("INSERT INTO [Directions]([DirectionId], [DirectionName], [Abbreviation], [IsCardinal], [PreviousDirectionId], [OppositeDirectionId], [NextDirectionId]) VALUES (@DirectionId, @DirectionName, @Abbreviation, @IsCardinal, @PreviousDirectionId, @OppositeDirectionId, @NextDirectionId);", connection)
            command.Parameters.AddWithValue("@DirectionId", DirectionId)
            command.Parameters.AddWithValue("@DirectionName", DirectionName)
            command.Parameters.AddWithValue("@Abbreviation", Abbreviation)
            command.Parameters.AddWithValue("@IsCardinal", IsCardinal)
            command.Parameters.AddWithValue("@PreviousDirectionId", If(PreviousDirectionId Is Nothing, CObj(DBNull.Value), PreviousDirectionId))
            command.Parameters.AddWithValue("@OppositeDirectionId", OppositeDirectionId)
            command.Parameters.AddWithValue("@NextDirectionId", If(NextDirectionId Is Nothing, CObj(DBNull.Value), NextDirectionId))
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateDirections(connection As SqliteConnection)
        PopulateDirectionsRecord(connection, 1, "North", "N", 1, 4, 3, 2)
        PopulateDirectionsRecord(connection, 2, "East", "E", 1, 1, 4, 3)
        PopulateDirectionsRecord(connection, 3, "South", "S", 1, 2, 1, 4)
        PopulateDirectionsRecord(connection, 4, "West", "W", 1, 3, 2, 1)
        PopulateDirectionsRecord(connection, 5, "Up", "U", 0, Nothing, 6, Nothing)
        PopulateDirectionsRecord(connection, 6, "Down", "D", 0, Nothing, 5, Nothing)
        PopulateDirectionsRecord(connection, 7, "In", "In", 0, Nothing, 8, Nothing)
        PopulateDirectionsRecord(connection, 8, "Out", "Out", 0, Nothing, 7, Nothing)
    End Sub
    Sub PopulateRouteTypesRecord(connection As SqliteConnection, RouteTypeId As Long, Abbreviation As String, IsSingleUse As Long)
        Using command = New SqliteCommand("INSERT INTO [RouteTypes]([RouteTypeId], [Abbreviation], [IsSingleUse]) VALUES (@RouteTypeId, @Abbreviation, @IsSingleUse);", connection)
            command.Parameters.AddWithValue("@RouteTypeId", RouteTypeId)
            command.Parameters.AddWithValue("@Abbreviation", Abbreviation)
            command.Parameters.AddWithValue("@IsSingleUse", IsSingleUse)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateRouteTypes(connection As SqliteConnection)
        PopulateRouteTypesRecord(connection, 1, "  ", 0)
        PopulateRouteTypesRecord(connection, 2, "  ", 0)
        PopulateRouteTypesRecord(connection, 3, "  ", 0)
        PopulateRouteTypesRecord(connection, 4, "FE", 0)
        PopulateRouteTypesRecord(connection, 5, "CU", 0)
        PopulateRouteTypesRecord(connection, 6, "AG", 0)
        PopulateRouteTypesRecord(connection, 7, "AU", 0)
        PopulateRouteTypesRecord(connection, 8, "PT", 0)
        PopulateRouteTypesRecord(connection, 9, "EO", 0)
        PopulateRouteTypesRecord(connection, 10, "  ", 1)
        PopulateRouteTypesRecord(connection, 11, "  ", 0)
    End Sub
    Sub PopulateRouteTypeLocksRecord(connection As SqliteConnection, RouteTypeId As Long, UnlockedRouteTypeId As Long, UnlockItemTypeId As Long)
        Using command = New SqliteCommand("INSERT INTO [RouteTypeLocks]([RouteTypeId], [UnlockedRouteTypeId], [UnlockItemTypeId]) VALUES (@RouteTypeId, @UnlockedRouteTypeId, @UnlockItemTypeId);", connection)
            command.Parameters.AddWithValue("@RouteTypeId", RouteTypeId)
            command.Parameters.AddWithValue("@UnlockedRouteTypeId", UnlockedRouteTypeId)
            command.Parameters.AddWithValue("@UnlockItemTypeId", UnlockItemTypeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateRouteTypeLocks(connection As SqliteConnection)
        PopulateRouteTypeLocksRecord(connection, 4, 2, 1)
        PopulateRouteTypeLocksRecord(connection, 5, 2, 2)
        PopulateRouteTypeLocksRecord(connection, 6, 2, 3)
        PopulateRouteTypeLocksRecord(connection, 7, 2, 4)
        PopulateRouteTypeLocksRecord(connection, 8, 2, 5)
        PopulateRouteTypeLocksRecord(connection, 9, 2, 6)
    End Sub
    Sub PopulateSpellTypesRecord(connection As SqliteConnection, SpellTypeId As Long, SpellTypeName As String, MaximumLevel As Long, CastCheck As String, Cast As String)
        Using command = New SqliteCommand("INSERT INTO [SpellTypes]([SpellTypeId], [SpellTypeName], [MaximumLevel], [CastCheck], [Cast]) VALUES (@SpellTypeId, @SpellTypeName, @MaximumLevel, @CastCheck, @Cast);", connection)
            command.Parameters.AddWithValue("@SpellTypeId", SpellTypeId)
            command.Parameters.AddWithValue("@SpellTypeName", SpellTypeName)
            command.Parameters.AddWithValue("@MaximumLevel", MaximumLevel)
            command.Parameters.AddWithValue("@CastCheck", CastCheck)
            command.Parameters.AddWithValue("@Cast", Cast)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateSpellTypes(connection As SqliteConnection)
        PopulateSpellTypesRecord(connection, 1, "Holy Bolt", 1, "CharacterCanCastHolyBolt", "CharacterCastHolyBolt")
        PopulateSpellTypesRecord(connection, 2, "Purify", 1, "CharacterCanCastPurify", "CharacterCastPurify")
    End Sub
    Sub PopulateSpellTypeRequiredPowersRecord(connection As SqliteConnection, SpellTypeId As Long, SpellLevel As Long, Power As Long)
        Using command = New SqliteCommand("INSERT INTO [SpellTypeRequiredPowers]([SpellTypeId], [SpellLevel], [Power]) VALUES (@SpellTypeId, @SpellLevel, @Power);", connection)
            command.Parameters.AddWithValue("@SpellTypeId", SpellTypeId)
            command.Parameters.AddWithValue("@SpellLevel", SpellLevel)
            command.Parameters.AddWithValue("@Power", Power)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateSpellTypeRequiredPowers(connection As SqliteConnection)
        PopulateSpellTypeRequiredPowersRecord(connection, 1, 0, 0)
        PopulateSpellTypeRequiredPowersRecord(connection, 1, 1, 1)
        PopulateSpellTypeRequiredPowersRecord(connection, 2, 0, 0)
        PopulateSpellTypeRequiredPowersRecord(connection, 2, 1, 0)
    End Sub
    Sub PopulateLocationsRecord(connection As SqliteConnection, LocationId As Long, LocationTypeId As Long)
        Using command = New SqliteCommand("INSERT INTO [Locations]([LocationId], [LocationTypeId]) VALUES (@LocationId, @LocationTypeId);", connection)
            command.Parameters.AddWithValue("@LocationId", LocationId)
            command.Parameters.AddWithValue("@LocationTypeId", LocationTypeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateLocations(connection As SqliteConnection)
    End Sub
    Sub PopulateCharactersRecord(connection As SqliteConnection, CharacterId As Long, LocationId As Long, CharacterTypeId As Long)
        Using command = New SqliteCommand("INSERT INTO [Characters]([CharacterId], [LocationId], [CharacterTypeId]) VALUES (@CharacterId, @LocationId, @CharacterTypeId);", connection)
            command.Parameters.AddWithValue("@CharacterId", CharacterId)
            command.Parameters.AddWithValue("@LocationId", LocationId)
            command.Parameters.AddWithValue("@CharacterTypeId", CharacterTypeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacters(connection As SqliteConnection)
    End Sub
    Sub PopulateCharacterLocationsRecord(connection As SqliteConnection, CharacterId As Long, LocationId As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterLocations]([CharacterId], [LocationId]) VALUES (@CharacterId, @LocationId);", connection)
            command.Parameters.AddWithValue("@CharacterId", CharacterId)
            command.Parameters.AddWithValue("@LocationId", LocationId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterLocations(connection As SqliteConnection)
    End Sub
    Sub PopulateCharacterSpellsRecord(connection As SqliteConnection, CharacterId As Long, SpellTypeId As Long, SpellLevel As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterSpells]([CharacterId], [SpellTypeId], [SpellLevel]) VALUES (@CharacterId, @SpellTypeId, @SpellLevel);", connection)
            command.Parameters.AddWithValue("@CharacterId", CharacterId)
            command.Parameters.AddWithValue("@SpellTypeId", SpellTypeId)
            command.Parameters.AddWithValue("@SpellLevel", SpellLevel)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterSpells(connection As SqliteConnection)
    End Sub
    Sub PopulatePlayersRecord(connection As SqliteConnection, PlayerId As Long, CharacterId As Long, DirectionId As Long, PlayerModeId As Long)
        Using command = New SqliteCommand("INSERT INTO [Players]([PlayerId], [CharacterId], [DirectionId], [PlayerModeId]) VALUES (@PlayerId, @CharacterId, @DirectionId, @PlayerModeId);", connection)
            command.Parameters.AddWithValue("@PlayerId", PlayerId)
            command.Parameters.AddWithValue("@CharacterId", CharacterId)
            command.Parameters.AddWithValue("@DirectionId", DirectionId)
            command.Parameters.AddWithValue("@PlayerModeId", PlayerModeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulatePlayers(connection As SqliteConnection)
    End Sub
    Sub PopulateItemsRecord(connection As SqliteConnection, ItemId As Long, ItemTypeId As Long)
        Using command = New SqliteCommand("INSERT INTO [Items]([ItemId], [ItemTypeId]) VALUES (@ItemId, @ItemTypeId);", connection)
            command.Parameters.AddWithValue("@ItemId", ItemId)
            command.Parameters.AddWithValue("@ItemTypeId", ItemTypeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItems(connection As SqliteConnection)
    End Sub
    Sub PopulateCharacterEquipSlotsRecord(connection As SqliteConnection, CharacterId As Long, EquipSlotId As Long, ItemId As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterEquipSlots]([CharacterId], [EquipSlotId], [ItemId]) VALUES (@CharacterId, @EquipSlotId, @ItemId);", connection)
            command.Parameters.AddWithValue("@CharacterId", CharacterId)
            command.Parameters.AddWithValue("@EquipSlotId", EquipSlotId)
            command.Parameters.AddWithValue("@ItemId", ItemId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterEquipSlots(connection As SqliteConnection)
    End Sub
    Sub PopulateCharacterQuestCompletionsRecord(connection As SqliteConnection, CharacterId As Long, QuestTypeId As Long, Completions As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterQuestCompletions]([CharacterId], [QuestTypeId], [Completions]) VALUES (@CharacterId, @QuestTypeId, @Completions);", connection)
            command.Parameters.AddWithValue("@CharacterId", CharacterId)
            command.Parameters.AddWithValue("@QuestTypeId", QuestTypeId)
            command.Parameters.AddWithValue("@Completions", Completions)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterQuestCompletions(connection As SqliteConnection)
    End Sub
    Sub PopulateCharacterQuestsRecord(connection As SqliteConnection, CharacterId As Long, QuestTypeId As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterQuests]([CharacterId], [QuestTypeId]) VALUES (@CharacterId, @QuestTypeId);", connection)
            command.Parameters.AddWithValue("@CharacterId", CharacterId)
            command.Parameters.AddWithValue("@QuestTypeId", QuestTypeId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterQuests(connection As SqliteConnection)
    End Sub
    Sub PopulateCharacterStatisticsRecord(connection As SqliteConnection, CharacterId As Long, CharacterStatisticTypeId As Long, StatisticValue As Long)
        Using command = New SqliteCommand("INSERT INTO [CharacterStatistics]([CharacterId], [CharacterStatisticTypeId], [StatisticValue]) VALUES (@CharacterId, @CharacterStatisticTypeId, @StatisticValue);", connection)
            command.Parameters.AddWithValue("@CharacterId", CharacterId)
            command.Parameters.AddWithValue("@CharacterStatisticTypeId", CharacterStatisticTypeId)
            command.Parameters.AddWithValue("@StatisticValue", StatisticValue)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateCharacterStatistics(connection As SqliteConnection)
    End Sub
    Sub PopulateInventoriesRecord(connection As SqliteConnection, InventoryId As Long, CharacterId As Long?, LocationId As Long?)
        Using command = New SqliteCommand("INSERT INTO [Inventories]([InventoryId], [CharacterId], [LocationId]) VALUES (@InventoryId, @CharacterId, @LocationId);", connection)
            command.Parameters.AddWithValue("@InventoryId", InventoryId)
            command.Parameters.AddWithValue("@CharacterId", If(CharacterId Is Nothing, CObj(DBNull.Value), CharacterId))
            command.Parameters.AddWithValue("@LocationId", If(LocationId Is Nothing, CObj(DBNull.Value), LocationId))
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateInventories(connection As SqliteConnection)
    End Sub
    Sub PopulateInventoryItemsRecord(connection As SqliteConnection, InventoryId As Long, ItemId As Long)
        Using command = New SqliteCommand("INSERT INTO [InventoryItems]([InventoryId], [ItemId]) VALUES (@InventoryId, @ItemId);", connection)
            command.Parameters.AddWithValue("@InventoryId", InventoryId)
            command.Parameters.AddWithValue("@ItemId", ItemId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateInventoryItems(connection As SqliteConnection)
    End Sub
    Sub PopulateItemStatisticsRecord(connection As SqliteConnection, ItemId As Long, ItemStatisticTypeId As Long, StatisticValue As Long)
        Using command = New SqliteCommand("INSERT INTO [ItemStatistics]([ItemId], [ItemStatisticTypeId], [StatisticValue]) VALUES (@ItemId, @ItemStatisticTypeId, @StatisticValue);", connection)
            command.Parameters.AddWithValue("@ItemId", ItemId)
            command.Parameters.AddWithValue("@ItemStatisticTypeId", ItemStatisticTypeId)
            command.Parameters.AddWithValue("@StatisticValue", StatisticValue)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateItemStatistics(connection As SqliteConnection)
    End Sub
    Sub PopulateLocationDungeonLevelsRecord(connection As SqliteConnection, LocationId As Long, DungeonLevelId As Long)
        Using command = New SqliteCommand("INSERT INTO [LocationDungeonLevels]([LocationId], [DungeonLevelId]) VALUES (@LocationId, @DungeonLevelId);", connection)
            command.Parameters.AddWithValue("@LocationId", LocationId)
            command.Parameters.AddWithValue("@DungeonLevelId", DungeonLevelId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateLocationDungeonLevels(connection As SqliteConnection)
    End Sub
    Sub PopulateFeaturesRecord(connection As SqliteConnection, FeatureId As Long, FeatureTypeId As Long, LocationId As Long)
        Using command = New SqliteCommand("INSERT INTO [Features]([FeatureId], [FeatureTypeId], [LocationId]) VALUES (@FeatureId, @FeatureTypeId, @LocationId);", connection)
            command.Parameters.AddWithValue("@FeatureId", FeatureId)
            command.Parameters.AddWithValue("@FeatureTypeId", FeatureTypeId)
            command.Parameters.AddWithValue("@LocationId", LocationId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateFeatures(connection As SqliteConnection)
    End Sub
    Sub PopulateLocationStatisticsRecord(connection As SqliteConnection, LocationId As Long, LocationStatisticTypeId As Long, StatisticValue As Long)
        Using command = New SqliteCommand("INSERT INTO [LocationStatistics]([LocationId], [LocationStatisticTypeId], [StatisticValue]) VALUES (@LocationId, @LocationStatisticTypeId, @StatisticValue);", connection)
            command.Parameters.AddWithValue("@LocationId", LocationId)
            command.Parameters.AddWithValue("@LocationStatisticTypeId", LocationStatisticTypeId)
            command.Parameters.AddWithValue("@StatisticValue", StatisticValue)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateLocationStatistics(connection As SqliteConnection)
    End Sub
    Sub PopulateRoutesRecord(connection As SqliteConnection, RouteId As Long, LocationId As Long, DirectionId As Long, RouteTypeId As Long, ToLocationId As Long)
        Using command = New SqliteCommand("INSERT INTO [Routes]([RouteId], [LocationId], [DirectionId], [RouteTypeId], [ToLocationId]) VALUES (@RouteId, @LocationId, @DirectionId, @RouteTypeId, @ToLocationId);", connection)
            command.Parameters.AddWithValue("@RouteId", RouteId)
            command.Parameters.AddWithValue("@LocationId", LocationId)
            command.Parameters.AddWithValue("@DirectionId", DirectionId)
            command.Parameters.AddWithValue("@RouteTypeId", RouteTypeId)
            command.Parameters.AddWithValue("@ToLocationId", ToLocationId)
            command.ExecuteNonQuery()
        End Using
    End Sub
    Sub PopulateRoutes(connection As SqliteConnection)
    End Sub
End Module
