# Prototype of the enum part of the task 27 exporter: writes content_stub.odin with enums (None = 0, value = VB id).
import re, sqlite3, sys
db = sqlite3.connect(sys.argv[1] if len(sys.argv) > 1 else "../../src/KordanorsCabal/boilerplate.db")
def ident(name, id_, seen):
    s = re.sub(r"[^0-9A-Za-z]+", "_", name).strip("_") or f"Id_{id_}"
    if s[0].isdigit(): s = "_" + s
    if s in seen: s = f"{s}_{id_}"
    seen.add(s)
    return s
def enum(type_name, table, id_col, name_col):
    seen = {"None"}
    out = [f"{type_name} :: enum u8 {{", "\tNone = 0,"]
    for id_, name in db.execute(f"select {id_col},{name_col} from {table} order by 1"):
        out.append(f"\t{ident(name, id_, seen)} = {id_},")
    out.append("}")
    return "\n".join(out)
parts = ["package main", "", "// GENERATED by gen_stub.py from boilerplate.db (spike). Values equal the original VB ids.", ""]
for args in [("Item_Type","ItemTypes","ItemTypeId","ItemTypeName"),("Character_Type","CharacterTypes","CharacterTypeId","CharacterTypeName"),
             ("Location_Type","LocationTypes","LocationTypeId","LocationTypeName"),("Feature_Type","FeatureTypes","FeatureTypeId","FeatureTypeName"),
             ("Equip_Slot","EquipSlots","EquipSlotId","EquipSlotName"),("Direction","Directions","DirectionId","DirectionName"),
             ("Stat","StatisticTypes","StatisticTypeId","CharacterStatisticTypeName"),("Dungeon_Level","DungeonLevels","DungeonLevelId","DungeonLevelName"),
             ("Shoppe_Type","ShoppeTypes","ShoppeTypeId","ShoppeTypeName"),("Spell_Type","SpellTypes","SpellTypeId","SpellTypeName")]:
    parts += [enum(*args), ""]
parts += ["Quest_Type :: enum u8 {\n\tNone = 0,\n\tCellar_Rats = 1,\n}", ""]
parts += ["Route_Type :: enum u8 {\n\tNone = 0,\n" + "".join(f"\tRoute_{i} = {i},\n" for i in range(1,12)) + "}", ""]
parts += ["Player_Mode :: enum u8 {\n\tNone = 0, Neutral, Turn, Move, Elder, InnKeeper, TownDrunk, Chicken, BlackMarket, BlackMage, Blacksmith, Constable, Healer,\n}", ""]
open("content_stub.odin", "w").write("\n".join(parts))
