Public Interface IWorldData
    ReadOnly Property Character As CharacterData
    ReadOnly Property CharacterEquipSlot As CharacterEquipSlotData
    ReadOnly Property CharacterLocation As CharacterLocationData
    ReadOnly Property CharacterQuestCompletion As CharacterQuestCompletionData
    ReadOnly Property CharacterQuest As CharacterQuestData
    ReadOnly Property CharacterSpell As CharacterSpellData
    ReadOnly Property CharacterStatistic As CharacterStatisticData
    ReadOnly Property CharacterStatisticType As CharacterStatisticTypeData
    ReadOnly Property CharacterType As ICharacterTypeData
    ReadOnly Property CharacterTypeAttackType As CharacterTypeAttackTypeData
    ReadOnly Property CharacterTypeBribe As CharacterTypeBribeData
    ReadOnly Property CharacterTypeEnemy As CharacterTypeEnemyData
    ReadOnly Property CharacterTypeInitialStatistic As CharacterTypeInitialStatisticData
    ReadOnly Property CharacterTypeLoot As CharacterTypeLootData
    ReadOnly Property CharacterTypePartingShot As CharacterTypePartingShotData
    ReadOnly Property CharacterTypeSpawnCount As CharacterTypeSpawnCountData
    ReadOnly Property CharacterTypeSpawnLocation As CharacterTypeSpawnLocationData
    ReadOnly Property Direction As DirectionData
    ReadOnly Property DungeonLevel As DungeonLevelData
    ReadOnly Property EquipSlot As EquipSlotData
    ReadOnly Property Feature As FeatureData
    ReadOnly Property FeatureType As FeatureTypeData
    ReadOnly Property Inventory As InventoryData
    ReadOnly Property InventoryItem As InventoryItemData
    ReadOnly Property Item As ItemData
    ReadOnly Property ItemStatistic As ItemStatisticData
    ReadOnly Property ItemType As ItemTypeData
    ReadOnly Property ItemTypeSpawnCount As ItemTypeSpawnCountData
    ReadOnly Property ItemTypeSpawnLocationType As ItemTypeSpawnLocationTypeData
    ReadOnly Property ItemTypeStatistic As ItemTypeStatisticData
    ReadOnly Property ItemTypeStatisticType As ItemTypeStatisticTypeData
    ReadOnly Property Location As LocationData
    ReadOnly Property LocationDungeonLevel As LocationDungeonLevelData
    ReadOnly Property LocationStatistic As LocationStatisticData
    ReadOnly Property LocationType As LocationTypeData
    ReadOnly Property Player As PlayerData
    ReadOnly Property Route As RouteData
End Interface
