Public Enum UIState
    None
    TitleScreen
    AboutScreen
    ConfirmQuit
    OptionsScreen
    ScreenSizer
    InstructionsScreen
    FinalizeCharacter
    Prolog
    SfxVolumizer
    MuxVolumizer
    InPlay
    LoadGameScreen
    GameMenuScreen
    SaveGameScreen
    ConfirmAbandonGame
    GroundInventory
    Inventory
    InteractItem
    Map
    Message
    Dead
    Status
    LevelUp
    Enemies
    Equipment
    EquipmentDetail
    ShoppeOffers
    ShoppeSell
    ShoppePrices
    ShoppeBuy
End Enum
