# Prototype of the events part of the task 27 exporter. Reads boilerplate.db and writes content_events.odin:
#   Check and Action enums (separate, so a content error is a compile or export error, not a runtime lookup failure),
#   and per-item-type event slots (Purify, Can_Use, Use, Decay). Add_To_Inventory (event id 5, unused) is dropped (D13).
import re, sqlite3, sys
db = sqlite3.connect(sys.argv[1] if len(sys.argv) > 1 else "../../src/KordanorsCabal/boilerplate.db")
def snake(name): return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name)
KIND = {1: "purify", 2: "can_use", 3: "use", 4: "decay"}
rows = db.execute("select ItemTypeId, EventId, EventName from ItemTypeEvents order by 1, 2").fetchall()
checks = sorted({snake(n) for _, e, n in rows if e == 2})
actions = sorted({snake(n) for _, e, n in rows if e != 2})
spells = db.execute("select [CastCheck],[Cast] from SpellTypes").fetchall()
quests = db.execute("select CanAcceptEventName,AcceptEventName,CanCompleteEventName,CompleteEventName from QuestTypes").fetchall()
for c, a in spells: checks.append(snake(c)); actions.append(snake(a))
for ca, a, cc, c in quests: checks += [snake(ca), snake(cc)]; actions += [snake(a), snake(c)]
actions.append("Location_Decay_Items")
checks, actions = sorted(set(checks)), sorted(set(actions))
item_names = {i: n for i, n in db.execute("select ItemTypeId, ItemTypeName from ItemTypes")}
stub = open("content_stub.odin").read()
type_ident = {}
for m in re.finditer(r"^\t(\w+) = (\d+),$", stub.split("Item_Type :: enum u8 {")[1].split("}")[0], re.M): type_ident[int(m.group(2))] = m.group(1)
out = ["package main", "", "// GENERATED by gen_events.py from boilerplate.db (spike).", ""]
out.append("Check :: enum u8 {\n\tNone,\n" + "".join(f"\t{c},\n" for c in checks) + "}\n")
out.append("Action :: enum u8 {\n\tNone,\n" + "".join(f"\t{a},\n" for a in actions) + "}\n")
out.append("Item_Events :: struct { purify: Action, can_use: Check, use: Action, decay: Action }\n")
out.append("ITEM_EVENTS := #partial [Item_Type]Item_Events{")
by_type = {}
for t, e, n in rows:
    if e == 5: continue
    by_type.setdefault(t, {})[KIND[e]] = snake(n)
for t in sorted(by_type):
    fields = ", ".join(f"{k} = .{v}" for k, v in by_type[t].items())
    out.append(f"\t.{type_ident[t]} = {{{fields}}},")
out.append("\t// Item types not listed have no events.\n}\n")
spell_rows = ", ".join(f"{{.{c}, .{a}}}" for c, a in [(snake(c), snake(a)) for c, a in spells])
out.append("Spell_Events :: struct { can_cast: Check, do_cast: Action }\nSPELL_EVENTS := #partial [Spell_Type]Spell_Events{ .None = {}, " + ", ".join(f".{n} = {{.{snake(c)}, .{snake(a)}}}" for (c, a), n in zip(spells, ["Holy_Bolt", "Purify"])) + " }\n")
def ident_of(table, id_col, name_col, enum_name):
    text = stub.split(enum_name + " :: enum u8 {")[1].split("}")[0]
    return {int(m.group(2)): m.group(1) for m in re.finditer(r"^\t(\w+) = (\d+),$", text, re.M)}
single = [type_ident[i] for (i,) in db.execute("select ItemTypeId from ItemTypeStatistics where StatisticTypeId=37 and StatisticValue=1 order by 1")]
out.append("SINGLE_USE :: bit_set[Item_Type]{" + ", ".join("." + n for n in single) + "}\n")
ctype = ident_of(None, None, None, "Character_Type")
bribes = {}
for c, i in db.execute("select CharacterTypeId, ItemTypeId from CharacterTypeBribes"): bribes.setdefault(c, []).append(type_ident[i])
out.append("BRIBES := #partial [Character_Type]bit_set[Item_Type]{")
for c in sorted(bribes): out.append(f"\t.{ctype[c]} = {{" + ", ".join("." + n for n in bribes[c]) + "},")
out.append("}\n")
ltype = ident_of(None, None, None, "Location_Type")
dung = [ltype[i] for (i,) in db.execute("select LocationTypeId from LocationTypes where IsDungeon=1")]
out.append("IS_DUNGEON :: bit_set[Location_Type]{" + ", ".join("." + n for n in dung) + "}\n")
esc = lambda t: '"' + t.replace("\\", "\\\\").replace('"', '\\"') + '"'
lores = db.execute("select LoreId, ItemName, LoreText from Lores order by 1").fetchall()
out.append(f"LORE_COUNT :: {len(lores)}")
out.append("LORE_ITEM_NAME := [LORE_COUNT + 1]string{\"\", " + ", ".join(esc(n) for _, n, _ in lores) + "}")
out.append("LORE_TEXT := [LORE_COUNT + 1]string{\"\", " + ", ".join(esc(t) for _, _, t in lores) + "}\n")
iname = {i: n for i, n in db.execute("select ItemTypeId, ItemTypeName from ItemTypes")}
cname = {i: n for i, n in db.execute("select CharacterTypeId, CharacterTypeName from CharacterTypes")}
out.append("ITEM_NAME := [Item_Type]string{\n\t.None = \"\",\n" + "".join(f"\t.{type_ident[i]} = {esc(iname[i])},\n" for i in sorted(iname)) + "}\n")
out.append("CHARACTER_NAME := [Character_Type]string{\n\t.None = \"\",\n" + "".join(f"\t.{ctype[i]} = {esc(cname[i])},\n" for i in sorted(cname)) + "}\n")
open("content_events.odin", "w").write("\n".join(out))
print(len(checks), "checks;", len(actions), "actions;", len(by_type), "item types with events")
