Module Columns
    Friend Const CharacterIdColumn = "CharacterId"
    Friend Const CharacterTypeIdColumn = "CharacterTypeId"
    Friend Const CompletionsColumn = "Completions"
    Friend Const EquipSlotColumn = "EquipSlot"
    Friend Const IsUndeadColumn = "IsUndead"
    Friend Const ItemIdColumn = "ItemId"
    Friend Const LocationIdColumn = "LocationId"
    Friend Const MoneyDropDiceColumn = "MoneyDropDice"
    Friend Const QuestColumn = "Quest"
    Friend Const SpellLevelColumn = "SpellLevel"
    Friend Const SpellTypeColumn = "SpellType"
    Friend Const StatisticValueColumn = "StatisticValue"
    Friend Const StatisticTypeColumn = "StatisticType"
End Module
