Module Columns
    Friend Const AbbreviationColumn = "Abbreviation"
    Friend Const AttackTypeColumn = "AttackType"
    Friend Const CharacterIdColumn = "CharacterId"
    Friend Const CharacterStatisticTypeIdColumn = "CharacterStatisticTypeId"
    Friend Const CharacterTypeIdColumn = "CharacterTypeId"
    Friend Const CharacterTypeNameColumn = "CharacterTypeName"
    Friend Const CompletionsColumn = "Completions"
    Friend Const DirectionIdColumn = "DirectionId"
    Friend Const DungeonLevelIdColumn = "DungeonLevelId"
    Friend Const EnemyCharacterTypeIdColumn = "EnemyCharacterTypeId"
    Friend Const EquipSlotColumn = "EquipSlot"
    Friend Const InitialValueColumn = "InitialValue"
    Friend Const IsUndeadColumn = "IsUndead"
    Friend Const ItemIdColumn = "ItemId"
    Friend Const ItemTypeIdColumn = "ItemTypeId"
    Friend Const LocationIdColumn = "LocationId"
    Friend Const LocationTypeIdColumn = "LocationTypeId"
    Friend Const MoneyDropDiceColumn = "MoneyDropDice"
    Friend Const PartingShotColumn = "PartingShot"
    Friend Const QuestColumn = "Quest"
    Friend Const SpawnCountColumn = "SpawnCount"
    Friend Const SpellLevelColumn = "SpellLevel"
    Friend Const SpellTypeColumn = "SpellType"
    Friend Const StatisticValueColumn = "StatisticValue"
    Friend Const WeightColumn = "Weight"
    Friend Const XPValueColumn = "XPValue"
End Module
