Module Tables
    Friend Const CharacterEquipSlots = "CharacterEquipSlots"
    Friend Const CharacterLocations = "CharacterLocations"
    Friend Const CharacterQuestCompletions = "CharacterQuestCompletions"
    Friend Const CharacterQuests = "CharacterQuests"
    Friend Const Characters = "Characters"
    Friend Const CharacterSpells = "CharacterSpells"
    Friend Const CharacterStatistics = "CharacterStatistics"
    Friend Const CharacterTypes = "CharacterTypes"
    Friend Const CharacterTypeAttackTypes = "CharacterTypeAttackTypes"
    Friend Const CharacterTypeBribes = "CharacterTypeBribes"
    Friend Const CharacterTypeEnemies = "CharacterTypeEnemies"
    Friend Const CharacterTypeInitialStatistics = "CharacterTypeInitialStatistics"
    Friend Const CharacterTypeLoots = "CharacterTypeLoots"
    Friend Const CharacterTypePartingShots = "CharacterTypePartingShots"
    Friend Const CharacterTypeSpawnCounts = "CharacterTypeSpawnCounts"
    Friend Const CharacterTypeSpawnLocations = "CharacterTypeSpawnLocations"
    Friend Const Directions = "Directions"
    Friend Const Inventories = "Inventories"
    Friend Const Players = "Players"
End Module
