Public Class CharacterTypeInitialStatisticData
    Inherits BaseData
    Friend Const TableName = "CharacterTypeInitialStatistics"
    Friend Const CharacterTypeIdColumn = CharacterTypeData.CharacterTypeIdColumn
    Friend Const CharacterStatisticTypeIdColumn = CharacterStatisticTypeData.CharacterStatisticTypeIdColumn
    Friend Const InitialValueColumn = "InitialValue"
    Friend Sub Initialize()
        Store.ExecuteNonQuery($"CREATE TABLE IF NOT EXISTS [{TableName}] AS
                WITH [cte](
                    [{CharacterTypeIdColumn}],
                    [{CharacterStatisticTypeIdColumn}],
                    [{InitialValueColumn}]) AS
                (VALUES
                    (1,11,2),
                    (1,1,6),
                    (1,2,2),
                    (1,6,2),
                    (1,23,0),
                    (1,3,0),
                    (1,7,2),
                    (1,13,0),
                    (1,10,3),
                    (1,4,2),
                    (1,12,0),
                    (2,11,1),
                    (2,1,4),
                    (2,2,2),
                    (2,6,2),
                    (2,23,0),
                    (2,3,0),
                    (2,7,3),
                    (2,13,0),
                    (2,10,2),
                    (2,4,3),
                    (2,12,0),
                    (3,11,2),
                    (3,1,2),
                    (3,2,4),
                    (3,6,1),
                    (3,23,0),
                    (3,3,0),
                    (3,7,1),
                    (3,13,0),
                    (3,10,1),
                    (3,4,1),
                    (3,12,0),
                    (4,11,3),
                    (4,1,6),
                    (4,2,3),
                    (4,6,4),
                    (4,23,0),
                    (4,3,6),
                    (4,7,3),
                    (4,13,0),
                    (4,10,3),
                    (4,4,3),
                    (4,12,0),
                    (5,11,4),
                    (5,1,8),
                    (5,2,4),
                    (5,6,5),
                    (5,23,0),
                    (5,3,6),
                    (5,7,3),
                    (5,13,0),
                    (5,10,4),
                    (5,4,3),
                    (5,12,0),
                    (6,11,1),
                    (6,1,4),
                    (6,2,1),
                    (6,6,1),
                    (6,23,0),
                    (6,3,0),
                    (6,7,1),
                    (6,13,0),
                    (6,10,2),
                    (6,4,1),
                    (6,12,0),
                    (7,11,1),
                    (7,1,6),
                    (7,2,1),
                    (7,6,2),
                    (7,23,0),
                    (7,3,1),
                    (7,7,1),
                    (7,13,0),
                    (7,10,3),
                    (7,4,2),
                    (7,12,0),
                    (8,11,5),
                    (8,1,8),
                    (8,2,5),
                    (8,6,10),
                    (8,23,0),
                    (8,3,4),
                    (8,7,4),
                    (8,13,0),
                    (8,10,4),
                    (8,4,4),
                    (8,12,0),
                    (9,11,2),
                    (9,1,6),
                    (9,2,4),
                    (9,6,2),
                    (9,23,0),
                    (9,3,1),
                    (9,7,1),
                    (9,13,0),
                    (9,10,3),
                    (9,4,2),
                    (9,12,0),
                    (10,11,4),
                    (10,1,8),
                    (10,2,4),
                    (10,6,3),
                    (10,23,0),
                    (10,3,6),
                    (10,7,3),
                    (10,13,0),
                    (10,10,4),
                    (10,4,3),
                    (10,12,0),
                    (11,11,1),
                    (11,22,0),
                    (11,2,1),
                    (11,18,0),
                    (11,15,0),
                    (11,21,0),
                    (11,19,0),
                    (11,6,3),
                    (11,23,0),
                    (11,20,0),
                    (11,3,1),
                    (11,8,1),
                    (11,14,0),
                    (11,7,3),
                    (11,5,1),
                    (11,1,1),
                    (11,13,0),
                    (11,10,1),
                    (11,9,8),
                    (11,4,1),
                    (11,12,0),
                    (11,16,0),
                    (11,17,10),
                    (11,24,50),
                    (11,25,10),
                    (12,11,3),
                    (12,1,6),
                    (12,2,3),
                    (12,6,3),
                    (12,23,0),
                    (12,3,3),
                    (12,7,3),
                    (12,13,0),
                    (12,10,3),
                    (12,4,3),
                    (12,12,0),
                    (13,11,1),
                    (13,1,2),
                    (13,2,1),
                    (13,6,1),
                    (13,23,0),
                    (13,3,0),
                    (13,7,1),
                    (13,13,0),
                    (13,10,1),
                    (13,4,1),
                    (13,12,0),
                    (14,11,2),
                    (14,1,4),
                    (14,2,2),
                    (14,6,1),
                    (14,23,0),
                    (14,10,2),
                    (14,12,0),
                    (15,11,1),
                    (15,1,3),
                    (15,2,1),
                    (15,6,1),
                    (15,23,0),
                    (15,3,0),
                    (15,7,1),
                    (15,13,0),
                    (15,10,2),
                    (15,4,1),
                    (15,12,0),
                    (16,11,3),
                    (16,1,4),
                    (16,2,3),
                    (16,6,1),
                    (16,23,0),
                    (16,10,2),
                    (16,12,0)
                )
                SELECT 
                    [{CharacterTypeIdColumn}],
                    [{CharacterStatisticTypeIdColumn}],
                    [{InitialValueColumn}]
                FROM [cte];")

    End Sub

    Public Function ReadAllForCharacterType(characterTypeId As Long) As List(Of Tuple(Of Long, Long))
        Return Store.ReadRecordsWithColumnValue(Of Long, Long, Long)(
            AddressOf Initialize,
            TableName,
            (CharacterStatisticTypeIdColumn, InitialValueColumn),
            (CharacterTypeIdColumn, characterTypeId))
    End Function

    Public Sub New(store As IStore, world As WorldData)
        MyBase.New(store, world)
    End Sub

    Public Function Read(characterTypeId As Long, statisticTypeId As Long) As Long?
        Return Store.ReadColumnValue(Of Long, Long, Long)(
            AddressOf Initialize,
            TableName,
            InitialValueColumn,
            (CharacterTypeIdColumn, characterTypeId),
            (CharacterStatisticTypeIdColumn, statisticTypeId))
    End Function

    Public Function ReadForCharacterType(characterTypeId As Long) As IEnumerable(Of Long)
        Return Store.ReadRecordsWithColumnValue(Of Long, Long)(
            AddressOf Initialize,
            TableName,
            CharacterStatisticTypeIdColumn,
            (CharacterTypeIdColumn, characterTypeId))
    End Function
End Class
